### ISSUE TITLE
Limit the maximum interface amount in single desire state.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1020]
Tested with PR #1016 , the 1000 interfaces could be a good baseline.

Things need to do:
 * Document in github page on maximum supported interface amount in single desire state.
 * Warn user in validation(or after merge) when interfaces amount exceeded 1000 is not supported.

**Comment by SudhanAruna** [comment]
Can I work on this ?

**Comment by SudhanAruna** [comment]
@ffmancera 
Can I work on this issue?

**Comment by cathay4t** [comment]
@SudhanAruna Sure. You can.

**Comment by SudhanAruna** [comment]
> 
> 
> @SudhanAruna Sure. You can.

Should I update in state examples document or nmstate readme file?
