### ISSUE TITLE
Integrate CentOS-stream into CI

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1028]
CentOS-stream now provides a newer NetworkManager version. Therefore it makes sense to include it in the CI.

**Comment by adwait-thattey** [comment]
Can I work on this?

**Comment by cathay4t** [comment]
> Can I work on this?

Sure. Please try to create a container of CentOS stream and use it as optional test along others.

**Comment by adwait-thattey** [comment]
@cathay4t There does not seem to be a docker image of centos-stream. 
Can you please tell me how I should build the container?
Thanks

**Comment by tyll** [comment]
> @cathay4t There does not seem to be a docker image of centos-stream.
> Can you please tell me how I should build the container?

You need to install centos-release-stream and then update all packages as far as I can tell.

**Comment by adwait-thattey** [comment]
I did that.
After installing `centos-release-stream` `NetworkManager-1.22.8` is being installed  
Without that, version `1.22.10` is installed which comes from the copr repository `networkmanager/NetworkManager-1.22` 

Am I supposed to test for `1.22.8` ?

**Comment by tyll** [comment]
> I did that.
> After installing `centos-release-stream` `NetworkManager-1.22.8` is being installed
> Without that, version `1.22.10` is installed which comes from the copr repository `networkmanager/NetworkManager-1.22`
> 
> Am I supposed to test for `1.22.8` ?

Yes, looks good. 1.22.8 is the version in CentOS-Stream but it contains patches that are not present in the upstream 1.22.10 version.
