### ISSUE TITLE
Does it work with remote hosts via TCP?

### ISSUE THREAD

**Issue by ieugen** [nmstate/nmstate#1076]
Hello,

Does it work for remote hosts via TCP? DBus can expose a TCP port. 

Can I point nmstatecli / libnmstate to that and use it to configure the host?

**Comment by ffmancera** [comment]
AFAIK, no. But I've never tried this so I will check it and let you know. Thanks!

**Comment by tyll** [comment]
Everything that is using sysfs/ethtool will not work via DBus.

**Comment by tyll** [comment]
Nmstate will soon be querying netlink to query the current networking state, therefore this will not work properly in the future. Varlink support for Nmstate is developed in #1081, so I guess remote management should be done via varlink in the future. Additionally, the ansible support in https://github.com/nmstate/ansible-nmstate could be updated. Therefore, I will close this issue. Please feel free to open a new issue or re-open this (if possible) if needed.
