### ISSUE TITLE
Need test case showing change IPv6 default gateway twice.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1077]
Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1837254 the NM will not remove old IPv6 default gateway at the second change of IPv6 default gateway.

When NM is fixing their bug, we should add test case to track it.

**Comment by ffmancera** [comment]
This was done by: `test_remove_default_ipv6_gateway_and_revert`
