### ISSUE TITLE
tests/integration/ovs_test.py::test_ovs_remove_port FAILED

### ISSUE THREAD

**Issue by vbenes** [nmstate/nmstate#1096]
https://desktopqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/beaker-NetworkManager-nm-1-24-veth-upstream/42/artifact/artifacts/FAIL_report_NetworkManager-ci_Test0486_nmstate.html

platform linux -- Python 3.6.8, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
RPMs: NetworkManager-1.24.3-25568.c1e5de0e30.el8.x86_64
OS: Red Hat Enterprise Linux 8.2 (Ootpa)
nmstate: nmstate-0.3.1-0.20200602.1098git74cbd30.el8.noarch
_____________________________ test_ovs_remove_port _____________________________

bridge_with_ports = <integration.testlib.ovslib.Bridge object at 0x7ffb35d2f0f0>

    @pytest.mark.tier1
    def test_ovs_remove_port(bridge_with_ports):
        for port_name in bridge_with_ports.ports_names:
            active_profiles = get_nm_active_profiles()
            assert port_name in active_profiles
            proxy_port_profile = get_proxy_port_profile_name_of_ovs_interface(
                port_name
            )
            assert proxy_port_profile
            assert proxy_port_profile in active_profiles
            libnmstate.apply(
                {
                    Interface.KEY: [
                        {
                            Interface.NAME: port_name,
                            Interface.STATE: InterfaceState.ABSENT,
                        }
                    ]
                }
            )
    
            with pytest.raises(CalledProcessError):
                cmdlib.exec_cmd(
                    f"nmcli connection show {proxy_port_profile}".split(" "),
>                   check=True,
                )
E               Failed: DID NOT RAISE <class 'subprocess.CalledProcessError'>

tests/integration/ovs_test.py:234: Failed
------------------------------ Captured log setup ------------------------------
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Add profile: eth1 started
DEBUG    root:context.py:157 Async action: Add profile: eth1 finished
DEBUG    root:context.py:148 Async action: Reapply device config: eth1 started
DEBUG    root:device.py:89 Device reapply failed on eth1: error=nm-device-error-quark: Device is not activated (4)
Fallback to device activation
DEBUG    root:context.py:148 Async action: Activate profile: eth1 started
DEBUG    root:connection.py:215 Connection activation initiated: dev=eth1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:317 Connection activation succeeded: dev=eth1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: eth1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/696 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/696 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/696 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/696 finished
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Add profile: br1 started
DEBUG    root:context.py:148 Async action: Update profile: eth1 started
DEBUG    root:context.py:148 Async action: Add profile: ovs1 started
DEBUG    root:context.py:148 Async action: Add profile: ovs-port-eth1 started
DEBUG    root:context.py:148 Async action: Add profile: ovs-port-ovs1 started
DEBUG    root:context.py:157 Async action: Update profile: eth1 finished
DEBUG    root:context.py:157 Async action: Add profile: br1 finished
DEBUG    root:context.py:157 Async action: Add profile: ovs1 finished
DEBUG    root:context.py:157 Async action: Add profile: ovs-port-eth1 finished
DEBUG    root:context.py:157 Async action: Add profile: ovs-port-ovs1 finished
DEBUG    root:context.py:148 Async action: Activate profile: br1 started
DEBUG    root:connection.py:215 Connection activation initiated: dev=br1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:317 Connection activation succeeded: dev=br1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_IP_CONFIG of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_MASTER | NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_MASTER_HAS_SLAVES of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: br1 finished
DEBUG    root:context.py:148 Async action: Activate profile: ovs-port-eth1 started
DEBUG    root:context.py:148 Async action: Activate profile: ovs-port-ovs1 started
DEBUG    root:connection.py:215 Connection activation initiated: dev=ovs-port-eth1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:215 Connection activation initiated: dev=ovs-port-ovs1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:317 Connection activation succeeded: dev=ovs-port-eth1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_IP_CONFIG of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_MASTER | NM_ACTIVATION_STATE_FLAG_IS_SLAVE | NM_ACTIVATION_STATE_FLAG_LAYER2_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: ovs-port-eth1 finished
DEBUG    root:connection.py:317 Connection activation succeeded: dev=ovs-port-ovs1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_IP_CONFIG of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_MASTER | NM_ACTIVATION_STATE_FLAG_IS_SLAVE | NM_ACTIVATION_STATE_FLAG_LAYER2_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: ovs-port-ovs1 finished
DEBUG    root:context.py:148 Async action: Activate profile: ovs1 started
DEBUG    root:connection.py:215 Connection activation initiated: dev=ovs1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:317 Connection activation succeeded: dev=ovs1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_SLAVE | NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: ovs1 finished
DEBUG    root:context.py:148 Async action: Reapply device config: eth1 started
DEBUG    root:context.py:157 Async action: Reapply device config: eth1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/697 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/697 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/697 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/697 finished
------------------------------ Captured log call -------------------------------
DEBUG    root:cmdlib.py:40 nmcli -g NAME connection show --active (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
DEBUG    root:cmdlib.py:40 nmcli -g connection.master connection show eth1 (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
DEBUG    root:cmdlib.py:40 nmcli -g NAME,DEVICE connection show (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Deactivate profile: eth1 started
DEBUG    root:context.py:148 Async action: Deactivate profile: ovs-port-eth1 started
DEBUG    root:active_connection.py:98 Connection deactivation succeeded on eth1
DEBUG    root:context.py:157 Async action: Deactivate profile: eth1 finished
DEBUG    root:active_connection.py:98 Connection deactivation succeeded on ovs-port-eth1
DEBUG    root:context.py:157 Async action: Deactivate profile: ovs-port-eth1 finished
DEBUG    root:context.py:148 Async action: Delete profile: eth1 started
DEBUG    root:context.py:148 Async action: Delete profile: ovs-port-eth1 started
DEBUG    root:context.py:157 Async action: Delete profile: eth1 finished
DEBUG    root:context.py:157 Async action: Delete profile: ovs-port-eth1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/698 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/698 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/698 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/698 finished
DEBUG    root:cmdlib.py:40 nmcli connection show ovs-port-eth1 (cwd None)
DEBUG    root:cmdlib.py:40 nmcli -g NAME connection show --active (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
DEBUG    root:cmdlib.py:40 nmcli -g connection.master connection show ovs1 (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
DEBUG    root:cmdlib.py:40 nmcli -g NAME,DEVICE connection show (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Deactivate profile: ovs1 started
DEBUG    root:context.py:148 Async action: Deactivate profile: ovs-port-ovs1 started
DEBUG    root:active_connection.py:98 Connection deactivation succeeded on ovs-port-ovs1
DEBUG    root:context.py:157 Async action: Deactivate profile: ovs-port-ovs1 finished
DEBUG    root:active_connection.py:98 Connection deactivation succeeded on ovs1
DEBUG    root:context.py:157 Async action: Deactivate profile: ovs1 finished
DEBUG    root:context.py:148 Async action: Delete profile: ovs1 started
DEBUG    root:context.py:157 Async action: Delete profile: ovs1 finished
DEBUG    root:context.py:148 Async action: Delete device: ovs-port-ovs1 started
DEBUG    root:device.py:139 Interface is not real anymore: iface=ovs-port-ovs1
DEBUG    root:device.py:141 Ignored error: nm-device-error-quark: This device is not a software device or is not realized (5)
DEBUG    root:context.py:157 Async action: Delete device: ovs-port-ovs1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/699 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/699 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/699 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/699 finished
DEBUG    root:cmdlib.py:40 nmcli connection show ovs-port-ovs1 (cwd None)
DEBUG    root:cmdlib.py:55 SUCCESS: <err> = b''; <rc> = 0
---------------------------- Captured log teardown -----------------------------
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Deactivate profile: br1 started
DEBUG    root:active_connection.py:98 Connection deactivation succeeded on br1
DEBUG    root:context.py:157 Async action: Deactivate profile: br1 finished
DEBUG    root:context.py:148 Async action: Delete profile: br1 started
DEBUG    root:context.py:157 Async action: Delete profile: br1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/700 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/700 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/700 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/700 finished
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/701 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/701 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/701 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/701 finished

**Comment by ffmancera** [comment]
This should be fixed by #1100. Thanks @cathay4t!

**Comment by ffmancera** [comment]
This issue is happening again. Reopening it and investigating it.
