### ISSUE TITLE
tests/integration/vxlan_test.py::test_rollback_for_vxlans FAILED

### ISSUE THREAD

**Issue by vbenes** [nmstate/nmstate#1097]
https://desktopqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/beaker-NetworkManager-master-veth-rhel8-upstream/1674/artifact/artifacts/FAIL_report_NetworkManager-ci_Test0486_nmstate.html

platform linux -- Python 3.6.8, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /bin/python
cachedir: .pytest_cache
RPMs: NetworkManager-1.25.1-25903.3957d40f54.el8.x86_64
OS: Red Hat Enterprise Linux 8.2 (Ootpa)
nmstate: nmstate-0.3.1-0.20200603.1098git74cbd30.el8.noarch

rootdir: /mnt/tests/NetworkManager-ci/nmstate, inifile: tox.ini
collecting ... collected 272 items / 3 deselected / 269 selected

___________________________ test_rollback_for_vxlans ___________________________

eth1_up = {'interfaces': [{'ipv4': {'dhcp': False, 'enabled': False}, 'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False}, 'mac-address': 'C6:0B:A3:D0:C2:53', 'mtu': 1500, ...}]}

    @pytest.mark.tier1
    def test_rollback_for_vxlans(eth1_up):
        ifname = eth1_up[Interface.KEY][0][Interface.NAME]
        current_state = libnmstate.show()
        desired_state = vxlans_up(
            [
                VxlanState(id=VXLAN1_ID, base_if=ifname, remote="192.168.100.1"),
                VxlanState(id=VXLAN2_ID, base_if=ifname, remote="192.168.100.2"),
            ]
        )
        desired_state[Interface.KEY][1]["invalid_key"] = "foo"
        with pytest.raises(NmstateVerificationError):
            libnmstate.apply(desired_state)
    
        time.sleep(5)  # Give some time for NetworkManager to rollback
        current_state_after_apply = libnmstate.show()
>       assert current_state == current_state_after_apply
E       AssertionError: assert {'dns-resolver': {'config': {'search': [], 'server': []},\n                  'running': {'search': ['openstacklocal'],\n                              'server': ['10.11.5.19', '10.5.30.45']}},\n 'interfaces': [{'ipv4': {'address': [{'ip': '10.0.137.90',\n                                       'prefix-length': 22}],\n                          'auto-dns': True,\n                          'auto-gateway': True,\n                          'auto-routes': True,\n                          'dhcp': True,\n                          'enabled': True},\n                 'ipv6': {'address': [{'ip': '2620:52:0:88:91ec:6a61:e47:14c6',\n                                       'prefix-length': 64},\n                                      {'ip': '2620:52:0:88:f816:3eff:fefe:d848',\n                                       'prefix-length': 64},\n                                      {'ip': 'fe80::f816:3eff:fefe:d848',\n                                       'prefix-length': 64}],\n                          'auto-dns': True,\n                          'auto-gateway': True,\n                          'auto-routes': True,\n                          'autoconf': True,\n                          'dhcp': True,\n                          'enabled': True},\n                 'mac-address': 'FA:16:3E:FE:D8:48',\n                 'mtu': 1500,\n                 'name': 'eth0',\n                 'state': 'up',\n                 'type': 'ethernet'},\n                {'ipv4': {'dhcp': False, 'enabled': False},\n                 'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False},\n                 'mac-address': 'C6:0B:A3:D0:C2:53',\n                 'mtu': 1500,\n                 'name': 'eth1',\n                 'state': 'up',\n                 'type': 'ethernet'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mac-address': '1E:B8:E7:20:31:39',\n                 'mtu': 1500,\n                 'name': 'eth1p',\n                 'state': 'down',\n                 'type': 'ethernet'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mac-address': 'AA:0D:A8:6D:64:57',\n                 'mtu': 1500,\n                 'name': 'eth2',\n                 'state': 'down',\n                 'type': 'ethernet'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mac-address': 'C2:6F:32:FA:11:86',\n                 'mtu': 1500,\n                 'name': 'eth2p',\n                 'state': 'down',\n                 'type': 'ethernet'},\n                {'bridge': {'options': {'group-forward-mask': 0,\n                                        'mac-ageing-time': 300,\n                                        'multicast-snooping': True,\n                                        'stp': {'enabled': True,\n                                                'forward-delay': 15,\n                                                'hello-time': 2,\n                                                'max-age': 20,\n                                                'priority': 32768}},\n                            'port': []},\n                 'ipv4': {'dhcp': False, 'enabled': False},\n                 'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False},\n                 'mtu': 1500,\n                 'name': 'linux-br0',\n                 'state': 'up',\n                 'type': 'linux-bridge'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mtu': 65536,\n                 'name': 'lo',\n                 'state': 'down',\n                 'type': 'unknown'}],\n 'route-rules': {'config': []},\n 'routes': {'config': [],\n            'running': [{'destination': '0.0.0.0/0',\n                         'metric': 100,\n                         'next-hop-address': '10.0.139.254',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '10.0.136.0/22',\n                         'metric': 100,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '169.254.169.254/32',\n                         'metric': 100,\n                         'next-hop-address': '10.0.137.87',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '2620:52:0:88::/64',\n                         'metric': 100,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': 'fe80::/64',\n                         'metric': 100,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': 'ff00::/8',\n                         'metric': 256,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 255}]}} == {'dns-resolver': {'config': {'search': [], 'server': []},\n                  'running': {'search': ['openstacklocal'],\n                              'server': ['10.11.5.19', '10.5.30.45']}},\n 'interfaces': [{'ipv4': {'address': [{'ip': '10.0.137.90',\n                                       'prefix-length': 22}],\n                          'auto-dns': True,\n                          'auto-gateway': True,\n                          'auto-routes': True,\n                          'dhcp': True,\n                          'enabled': True},\n                 'ipv6': {'address': [{'ip': '2620:52:0:88:91ec:6a61:e47:14c6',\n                                       'prefix-length': 64},\n                                      {'ip': '2620:52:0:88:f816:3eff:fefe:d848',\n                                       'prefix-length': 64},\n                                      {'ip': 'fe80::f816:3eff:fefe:d848',\n                                       'prefix-length': 64}],\n                          'auto-dns': True,\n                          'auto-gateway': True,\n                          'auto-routes': True,\n                          'autoconf': True,\n                          'dhcp': True,\n                          'enabled': True},\n                 'mac-address': 'FA:16:3E:FE:D8:48',\n                 'mtu': 1500,\n                 'name': 'eth0',\n                 'state': 'up',\n                 'type': 'ethernet'},\n                {'ipv4': {'dhcp': False, 'enabled': False},\n                 'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False},\n                 'mac-address': 'C6:0B:A3:D0:C2:53',\n                 'mtu': 1500,\n                 'name': 'eth1',\n                 'state': 'up',\n                 'type': 'ethernet'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mac-address': '1E:B8:E7:20:31:39',\n                 'mtu': 1500,\n                 'name': 'eth1p',\n                 'state': 'down',\n                 'type': 'ethernet'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mac-address': 'AA:0D:A8:6D:64:57',\n                 'mtu': 1500,\n                 'name': 'eth2',\n                 'state': 'down',\n                 'type': 'ethernet'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mac-address': 'C2:6F:32:FA:11:86',\n                 'mtu': 1500,\n                 'name': 'eth2p',\n                 'state': 'down',\n                 'type': 'ethernet'},\n                {'bridge': {'options': {'group-forward-mask': 0,\n                                        'mac-ageing-time': 300,\n                                        'multicast-snooping': True,\n                                        'stp': {'enabled': True,\n                                                'forward-delay': 15,\n                                                'hello-time': 2,\n                                                'max-age': 20,\n                                                'priority': 32768}},\n                            'port': []},\n                 'ipv4': {'dhcp': False, 'enabled': False},\n                 'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False},\n                 'mtu': 1500,\n                 'name': 'linux-br0',\n                 'state': 'up',\n                 'type': 'linux-bridge'},\n                {'ipv4': {'enabled': False},\n                 'ipv6': {'enabled': False},\n                 'mtu': 65536,\n                 'name': 'lo',\n                 'state': 'down',\n                 'type': 'unknown'}],\n 'route-rules': {'config': []},\n 'routes': {'config': [],\n            'running': [{'destination': '0.0.0.0/0',\n                         'metric': 100,\n                         'next-hop-address': '10.0.139.254',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '10.0.136.0/22',\n                         'metric': 100,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '169.254.169.254/32',\n                         'metric': 100,\n                         'next-hop-address': '10.0.137.87',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '2620:52:0:88::/64',\n                         'metric': 100,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '::/0',\n                         'metric': 100,\n                         'next-hop-address': 'fe80::4e16:fc01:d83:88aa',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': '::/0',\n                         'metric': 100,\n                         'next-hop-address': 'fe80::4e16:fc01:d8c:98ed',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': 'fe80::/64',\n                         'metric': 100,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 254},\n                        {'destination': 'ff00::/8',\n                         'metric': 256,\n                         'next-hop-address': '',\n                         'next-hop-interface': 'eth0',\n                         'table-id': 255}]}}
E         Common items:
E         {'dns-resolver': {'config': {'search': [], 'server': []},
E                           'running': {'search': ['openstacklocal'],
E                                       'server': ['10.11.5.19', '10.5.30.45']}},
E          'interfaces': [{'ipv4': {'address': [{'ip': '10.0.137.90',
E                                                'prefix-length': 22}],
E                                   'auto-dns': True,
E                                   'auto-gateway': True,
E                                   'auto-routes': True,
E                                   'dhcp': True,
E                                   'enabled': True},
E                          'ipv6': {'address': [{'ip': '2620:52:0:88:91ec:6a61:e47:14c6',
E                                                'prefix-length': 64},
E                                               {'ip': '2620:52:0:88:f816:3eff:fefe:d848',
E                                                'prefix-length': 64},
E                                               {'ip': 'fe80::f816:3eff:fefe:d848',
E                                                'prefix-length': 64}],
E                                   'auto-dns': True,
E                                   'auto-gateway': True,
E                                   'auto-routes': True,
E                                   'autoconf': True,
E                                   'dhcp': True,
E                                   'enabled': True},
E                          'mac-address': 'FA:16:3E:FE:D8:48',
E                          'mtu': 1500,
E                          'name': 'eth0',
E                          'state': 'up',
E                          'type': 'ethernet'},
E                         {'ipv4': {'dhcp': False, 'enabled': False},
E                          'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False},
E                          'mac-address': 'C6:0B:A3:D0:C2:53',
E                          'mtu': 1500,
E                          'name': 'eth1',
E                          'state': 'up',
E                          'type': 'ethernet'},
E                         {'ipv4': {'enabled': False},
E                          'ipv6': {'enabled': False},
E                          'mac-address': '1E:B8:E7:20:31:39',
E                          'mtu': 1500,
E                          'name': 'eth1p',
E                          'state': 'down',
E                          'type': 'ethernet'},
E                         {'ipv4': {'enabled': False},
E                          'ipv6': {'enabled': False},
E                          'mac-address': 'AA:0D:A8:6D:64:57',
E                          'mtu': 1500,
E                          'name': 'eth2',
E                          'state': 'down',
E                          'type': 'ethernet'},
E                         {'ipv4': {'enabled': False},
E                          'ipv6': {'enabled': False},
E                          'mac-address': 'C2:6F:32:FA:11:86',
E                          'mtu': 1500,
E                          'name': 'eth2p',
E                          'state': 'down',
E                          'type': 'ethernet'},
E                         {'bridge': {'options': {'group-forward-mask': 0,
E                                                 'mac-ageing-time': 300,
E                                                 'multicast-snooping': True,
E                                                 'stp': {'enabled': True,
E                                                         'forward-delay': 15,
E                                                         'hello-time': 2,
E                                                         'max-age': 20,
E                                                         'priority': 32768}},
E                                     'port': []},
E                          'ipv4': {'dhcp': False, 'enabled': False},
E                          'ipv6': {'autoconf': False, 'dhcp': False, 'enabled': False},
E                          'mtu': 1500,
E                          'name': 'linux-br0',
E                          'state': 'up',
E                          'type': 'linux-bridge'},
E                         {'ipv4': {'enabled': False},
E                          'ipv6': {'enabled': False},
E                          'mtu': 65536,
E                          'name': 'lo',
E                          'state': 'down',
E                          'type': 'unknown'}],
E          'route-rules': {'config': []}}
E         Differing items:
E         {'routes': {'config': [], 'running': [{'destination': '0.0.0.0/0', 'metric': 100, 'next-hop-address': '10.0.139.254', ... 'eth0', ...}, {'destination': 'ff00::/8', 'metric': 256, 'next-hop-address': '', 'next-hop-interface': 'eth0', ...}]}} != {'routes': {'config': [], 'running': [{'destination': '0.0.0.0/0', 'metric': 100, 'next-hop-address': '10.0.139.254', ...ion': '::/0', 'metric': 100, 'next-hop-address': 'fe80::4e16:fc01:d8c:98ed', 'next-hop-interface': 'eth0', ...}, ...]}}
E         Full diff:
E           {
E            'dns-resolver': {'config': {'search': [],
E                                        'server': []},
E                             'running': {'search': ['openstacklocal'],
E                                         'server': ['10.11.5.19',
E                                                    '10.5.30.45']}},
E            'interfaces': [{'ipv4': {'address': [{'ip': '10.0.137.90',
E                                                  'prefix-length': 22}],
E                                     'auto-dns': True,
E                                     'auto-gateway': True,
E                                     'auto-routes': True,
E                                     'dhcp': True,
E                                     'enabled': True},
E                            'ipv6': {'address': [{'ip': '2620:52:0:88:91ec:6a61:e47:14c6',
E                                                  'prefix-length': 64},
E                                                 {'ip': '2620:52:0:88:f816:3eff:fefe:d848',
E                                                  'prefix-length': 64},
E                                                 {'ip': 'fe80::f816:3eff:fefe:d848',
E                                                  'prefix-length': 64}],
E                                     'auto-dns': True,
E                                     'auto-gateway': True,
E                                     'auto-routes': True,
E                                     'autoconf': True,
E                                     'dhcp': True,
E                                     'enabled': True},
E                            'mac-address': 'FA:16:3E:FE:D8:48',
E                            'mtu': 1500,
E                            'name': 'eth0',
E                            'state': 'up',
E                            'type': 'ethernet'},
E                           {'ipv4': {'dhcp': False,
E                                     'enabled': False},
E                            'ipv6': {'autoconf': False,
E                                     'dhcp': False,
E                                     'enabled': False},
E                            'mac-address': 'C6:0B:A3:D0:C2:53',
E                            'mtu': 1500,
E                            'name': 'eth1',
E                            'state': 'up',
E                            'type': 'ethernet'},
E                           {'ipv4': {'enabled': False},
E                            'ipv6': {'enabled': False},
E                            'mac-address': '1E:B8:E7:20:31:39',
E                            'mtu': 1500,
E                            'name': 'eth1p',
E                            'state': 'down',
E                            'type': 'ethernet'},
E                           {'ipv4': {'enabled': False},
E                            'ipv6': {'enabled': False},
E                            'mac-address': 'AA:0D:A8:6D:64:57',
E                            'mtu': 1500,
E                            'name': 'eth2',
E                            'state': 'down',
E                            'type': 'ethernet'},
E                           {'ipv4': {'enabled': False},
E                            'ipv6': {'enabled': False},
E                            'mac-address': 'C2:6F:32:FA:11:86',
E                            'mtu': 1500,
E                            'name': 'eth2p',
E                            'state': 'down',
E                            'type': 'ethernet'},
E                           {'bridge': {'options': {'group-forward-mask': 0,
E                                                   'mac-ageing-time': 300,
E                                                   'multicast-snooping': True,
E                                                   'stp': {'enabled': True,
E                                                           'forward-delay': 15,
E                                                           'hello-time': 2,
E                                                           'max-age': 20,
E                                                           'priority': 32768}},
E                                       'port': []},
E                            'ipv4': {'dhcp': False,
E                                     'enabled': False},
E                            'ipv6': {'autoconf': False,
E                                     'dhcp': False,
E                                     'enabled': False},
E                            'mtu': 1500,
E                            'name': 'linux-br0',
E                            'state': 'up',
E                            'type': 'linux-bridge'},
E                           {'ipv4': {'enabled': False},
E                            'ipv6': {'enabled': False},
E                            'mtu': 65536,
E                            'name': 'lo',
E                            'state': 'down',
E                            'type': 'unknown'}],
E            'route-rules': {'config': []},
E            'routes': {'config': [],
E                       'running': [{'destination': '0.0.0.0/0',
E                                    'metric': 100,
E                                    'next-hop-address': '10.0.139.254',
E                                    'next-hop-interface': 'eth0',
E                                    'table-id': 254},
E                                   {'destination': '10.0.136.0/22',
E                                    'metric': 100,
E                                    'next-hop-address': '',
E                                    'next-hop-interface': 'eth0',
E                                    'table-id': 254},
E                                   {'destination': '169.254.169.254/32',
E                                    'metric': 100,
E                                    'next-hop-address': '10.0.137.87',
E                                    'next-hop-interface': 'eth0',
E                                    'table-id': 254},
E                                   {'destination': '2620:52:0:88::/64',
E                                    'metric': 100,
E                                    'next-hop-address': '',
E                                    'next-hop-interface': 'eth0',
E                                    'table-id': 254},
E         -                         {'destination': '::/0',
E         -                          'metric': 100,
E         -                          'next-hop-address': 'fe80::4e16:fc01:d83:88aa',
E         -                          'next-hop-interface': 'eth0',
E         -                          'table-id': 254},
E         -                         {'destination': '::/0',
E         -                          'metric': 100,
E         -                          'next-hop-address': 'fe80::4e16:fc01:d8c:98ed',
E         -                          'next-hop-interface': 'eth0',
E         -                          'table-id': 254},
E                                   {'destination': 'fe80::/64',
E                                    'metric': 100,
E                                    'next-hop-address': '',
E                                    'next-hop-interface': 'eth0',
E                                    'table-id': 254},
E                                   {'destination': 'ff00::/8',
E                                    'metric': 256,
E                                    'next-hop-address': '',
E                                    'next-hop-interface': 'eth0',
E                                    'table-id': 255}]},
E           }

tests/integration/vxlan_test.py:86: AssertionError
------------------------------ Captured log setup ------------------------------
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Add profile: eth1 started
DEBUG    root:context.py:157 Async action: Add profile: eth1 finished
DEBUG    root:context.py:148 Async action: Reapply device config: eth1 started
DEBUG    root:device.py:89 Device reapply failed on eth1: error=nm-device-error-quark: Device is not activated (4)
Fallback to device activation
DEBUG    root:context.py:148 Async action: Activate profile: eth1 started
DEBUG    root:connection.py:215 Connection activation initiated: dev=eth1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:317 Connection activation succeeded: dev=eth1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: eth1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/996 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/996 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/996 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/996 finished
------------------------------ Captured log call -------------------------------
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Add profile: eth1.201 started
DEBUG    root:context.py:148 Async action: Add profile: eth1.202 started
DEBUG    root:context.py:157 Async action: Add profile: eth1.201 finished
DEBUG    root:context.py:157 Async action: Add profile: eth1.202 finished
DEBUG    root:context.py:148 Async action: Activate profile: eth1.201 started
DEBUG    root:context.py:148 Async action: Activate profile: eth1.202 started
DEBUG    root:connection.py:215 Connection activation initiated: dev=eth1.201, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:215 Connection activation initiated: dev=eth1.202, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
DEBUG    root:connection.py:317 Connection activation succeeded: dev=eth1.201, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: eth1.201 finished
DEBUG    root:connection.py:317 Connection activation succeeded: dev=eth1.202, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
DEBUG    root:context.py:157 Async action: Activate profile: eth1.202 finished
DEBUG    root:checkpoint.py:163 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/997 rollback executed
DEBUG    root:context.py:148 Async action: Rollback to checkpoint /org/freedesktop/NetworkManager/Checkpoint/997 started
DEBUG    root:checkpoint.py:234 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/997 rollback executed
DEBUG    root:checkpoint.py:252 Interface eth1p rollback succeeded
DEBUG    root:checkpoint.py:252 Interface linux-br0 rollback succeeded
DEBUG    root:checkpoint.py:252 Interface eth0 rollback succeeded
DEBUG    root:checkpoint.py:252 Interface eth2 rollback succeeded
DEBUG    root:checkpoint.py:252 Interface lo rollback succeeded
DEBUG    root:checkpoint.py:252 Interface eth2p rollback succeeded
DEBUG    root:checkpoint.py:252 Interface eth1 rollback succeeded
DEBUG    root:context.py:157 Async action: Rollback to checkpoint /org/freedesktop/NetworkManager/Checkpoint/997 finished
---------------------------- Captured log teardown -----------------------------
DEBUG    root:context.py:148 Async action: Create checkpoint started
DEBUG    root:checkpoint.py:177 Checkpoint None created for all devices
DEBUG    root:context.py:157 Async action: Create checkpoint finished
DEBUG    root:context.py:148 Async action: Deactivate profile: eth1 started
DEBUG    root:active_connection.py:98 Connection deactivation succeeded on eth1
DEBUG    root:context.py:157 Async action: Deactivate profile: eth1 finished
DEBUG    root:context.py:148 Async action: Delete profile: eth1 started
DEBUG    root:context.py:157 Async action: Delete profile: eth1 finished
DEBUG    root:checkpoint.py:140 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/998 destroyed
DEBUG    root:context.py:148 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/998 started
DEBUG    root:checkpoint.py:258 Checkpoint /org/freedesktop/NetworkManager/Checkpoint/998 destroy executed
DEBUG    root:context.py:157 Async action: Destroy checkpoint /org/freedesktop/NetworkManager/Checkpoint/998 finished

**Comment by ffmancera** [comment]
This should be fixed by #1100 and #1103.
