### ISSUE TITLE
NM: Delete existing profile which is targeting the MAC address instead of interface name.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1104]
In the `nm/applier.py` we will delete all existing profiles which are targeting the same interface name before creating new.

NM allows matching interface with MAC address `802-3-ethernet.mac-address` only instead of interface name.

Hence we need to delete those existing profiles also.

**Comment by ffmancera** [comment]
This is just outdated. We do not have this problem anymore.
