### ISSUE TITLE
LLDP Test: Add an assertion that only one neighbor is reported when injecting the test packet

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1119]
Currently, the code only checks for the length after doing some filtering but such an assertion is needed for the unfiltered report as well.
https://github.com/nmstate/nmstate/blob/b0f1b2623d7a7ea4e447c5b72a18e482d47d92bc/tests/integration/lldp_test.py#L161

**Comment by UnversedBlood** [comment]
I'd like to work on this issue.
