### ISSUE TITLE
Rewrite NM profile activation

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1129]
Current code issues:

In order to make things easier I am adding more details to this task. We are considering this issue as done when the proposed PRs would cover the following requirements.

* [x] Unify the profile activation logic in a single file.
* [x] Do not use import_by_id() and import_by_device().
* [x] Create a class keeping always the NM.SimpleConnection or NM.RemoteConnection. 
* [x] If it is needed to import the connection, use the uuid.

Demo is at https://github.com/cathay4t/nmstate/blob/plugin/libnmstate2/plugins/nm/profile.py

Update:

The NmProfile still holding too much non-used public interface.
And it's a mess when using pending_actions, sounds like you are maintaining a async queue.

Before you spend time on coding, you should design the workflow and interfaces.

This is what I design for this whole mess, let me know if that is too complex for you.
Design

    The iface or iface_staet is for object of BaseIface and its child.

    The iface_info is for dictionary. Should use iface when possible.

    nm/ovs.py provide NmOvsPortIface and NmOvsBondIface, so that
    proxy profiles does not require special attention in NmProfile.

    nm/profiles.py hold NmProfiles for inter-profile actions.

    nm/profile.py hold NmProfile for NM.RemoteConnection and
    NM.SimpleConnection modification.

    nm/profile_state.py hold NmProfileState providing join state
    parsing of NM.Device, NM.ActiveConneciton.

    For any action only require understanding of NM.Device and iface, save
    the code in nm/device.py

    For any action only requires understanding of NM.ActiveConneciton and
    iface, save it to nm/active_connection.py

    For any action only requires understanding of NM.SimpleConnection or
    NM.RemoteConnection and iface, save it to nm/connection.py.

NmOvsPortIface and NmOvsBondIface in nm/ovs.py

Base on BaseIface
NmProfiles in nm/profiles.py

Handle inter-profiles actions.
Public interfaces:

    __init__(context)
    apply_config(net_state, save_to_disk)
        Create NmOvsPortIface iface and change controller/subordinate
        status in net_state. So that OVS proxy inteface can be proceesed
        like other profiles.
        Create profile(s) for each iface.
        For each profile, invoke profile.save(). Wait all finish.
        Thomas said, creating profiles does not have validation, so the
        order does matters.
        Group profiles for pending actions.
            match iface.state {
            UP => NmProfile.activate()
            DOWN => NmProfile.deactivate()
            ABSENT => NmProfile.delete()
            }
        Wait each group to finish their actions.

Internal interfaces:

* `self._group_profiles_for_action() -> groups`
* `Nm.Profiles._apply_group_actions(groups)

NmProfile in nm/profile.py

Responsible for profile modification.
Public interfaces:

* `__init__(context, iface, save_to_disk)`
    * The caller should perpare the `BaseIface` even with name only.
    * Load `self._nm_remote_conn`
    * Load `self._nm_dev`
    * Load `self._nm_ac`

* `save(self)`:
    * If `save_to_disk`, `delete_iface_profiles_except()`
      self._nm_remote_conn to edit. Just queue the action in context.
    * If `self._nm_remote_conn` is None, `self._create_profile()` and save it
      to `self._simple_conn`. Queue the action in context.

* `activate(self)`
    * If `self._nm_remote_conn` is None, load it base on uuid of
      `self._simple_conn`.

    * If `self._nm_ac` is None, call
      `NM.Client.activate_connection_async()`.
      In its callback, call `NmProfileState.wait_activation()`.

    * If `self._nm_ac` is not None, call
      `NM.Device.reapply_async()`.
      In its callback, if fail, set self._nm_ac to None, and call
      `self.activate()`, if pass, call `NmDeviceState.wait_activation()`.

* `deactivate(self)`
    * if `self._nm_ac` is not None, call
      `NM.Client.deactivate_connection_async()`.

* `delete(self)`
    * `self.deactivate()`
    * if `self._nm_remote_conn` is not None, call
        `NM.RemoteConnection.delete_async()`
    * if `self._iface.is_virtual()`, call `NM.Device.delete_async()`.

Internal interfaces

* `_create_profile(self)`
    # Save `NM.SimpleConnection` to `self._simple_conn`
    # Code save the real code into `nm/connection.py` as

NmDeviceState

* `__init__(self, context, nm_dev, nm_remote_conn=None)`

* `wait_activation(self)`
    # This will be used by rollback also.
    # The code for checking is activated or not could be saved in
    # `nm/active_connection.py` or other place.
    # If self._nm_remote_conn, check whether activated connection is
    # wait requested.

* `is_activated(self)`
    # True or false.

**Comment by ffmancera** [comment]
In order to make things easier I am adding more details to this task. We are considering this issue as done when the proposed PRs would cover the following requirements.

* [ ] Unify the profile activation logic in a single file.
* [ ] Do not use import_by_id() and import_by_device().
* [ ] Create a class keeping always the NM.SimpleConnection or NM.RemoteConnection. 
* [ ] If it is needed to import the connection, use the uuid.
