### ISSUE TITLE
Support querying saved config.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1130]
API example: 

 * `show_saved_config()`: Showing config used for next boot without state data.

**Comment by ffmancera** [comment]
Running config support done and merged. For saved config support there is a bug on NetworkManager and there is not workaround available. 

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1913551

**Comment by ffmancera** [comment]
Is a nice to have, closing it until someone ask for it explicitly.
