### ISSUE TITLE
Add GitHub template to report a bug

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1154]
Since we have a template for new releases, creating a normal issue is less obvious. Therefore it is probably a good idea to add a template to report a bug and request infos like:

- version/commit of nmstate
- distribution
- NetworkManager version
- state that was used to trigger the issue as yaml
- nmstatectl output (current/expected)
- ...

**Comment by UnversedBlood** [comment]
I'd like to work on this issue

**Comment by ffmancera** [comment]
Done by #1166, thanks!
