### ISSUE TITLE
run-tests.sh does not install dependencies for nmstate

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1191]
Instead of using yum, which would resolve dependencies, run-tests.sh uses rpm in https://github.com/nmstate/nmstate/blob/1f45a654e23d223962aeb3be6500dc0fa47df9f1/automation/run-tests.sh#L85 to install the nmstate rpm. Therefore, python3-varlink is not installed automatically, see the CI error for #1081 - https://travis-ci.com/github/nmstate/nmstate/jobs/357841849

```
error: Failed dependencies:
2035	python3.6dist(varlink) is needed by python3-libnmstate-0.4.0-0.20200706.52gitac07286.el8.noarch
```

Using yum would allow to reduce the number of packages from the container spec so that the dependencies from the RPM would also be tested in the CI but it will increase the test time when they are not specified.

**Comment by cathay4t** [comment]
Using `rpm` directly can speed up the package installing speed a lot without refreshing dnf caches.

For the dependency, it's the job of `Dockerfile` or other script.

**Comment by cathay4t** [comment]
PR #1081 should include `python3-varlink` in CI Dockerfiles.

**Comment by SudhanAruna** [comment]
> PR #1081 should include `python3-varlink` in CI Dockerfiles.
python3-varlink (29.0.0) is not update to new version. In the varlink implementation we require version 30.3.0 or greater than 30.1.0. This is reason for using pypi package to install dependency.
