### ISSUE TITLE
nmstate-plugin-ovsdb should require python3dist(ovs)

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#1203]
## Describe the bug
In `nmstate.spec`, nmstate-plugin-ovsdb subpackage is recommending `python3dist(ovs)` instead it should require it. In addition, python3-nmstate is recommending `NetworkManager` as we are not using dbus directly anymore, we should require it too.

Ref: http://ftp.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html

**Comment by Razaloc** [comment]
Can I work on this?

**Comment by ffmancera** [comment]
> Can I work on this?

Sure!
