### ISSUE TITLE
Need manpage for `nmstatectl varlink`

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1289]

**Comment by SudhanAruna** [comment]
@cathay4t 
Can I work on this issue?

**Comment by ffmancera** [comment]
@SudhanAruna Yes, please do. Thanks!

**Comment by SudhanAruna** [comment]
@cathay4t @ffmancera 
Should it be separate man page for nmstate-varlink or shall I include in nmstatectl?
