### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#1296]
I've been reading https://github.com/linux-system-roles/network/blob/main/contributing.md and I liked it a lot. The idea is to improve our current CONTRIBUTING.md file, including:

* [x] Include the code structure.
* [x] How to configure git, including a reference to Pro Git would be a great idea.
* [x] How to write a good commit message.
* [x] Include reference to our developer guide https://www.nmstate.io/devel/dev_guide.html
* [x] commit-template.txt is mentioned in CONTRIBUTING.md but does not seem to exist. Remove it please.

**Comment by ffmancera** [comment]
@Razaloc would you like to work on this? Thanks!

**Comment by Razaloc** [comment]
Yes, thanks
