### ISSUE TITLE
Use nispor for querying IP over InfiniBand

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1352]
Currently, due to kernel bug(no link or commit yet),  the kernel will not provide netlink information for ipoib interface which is created by NetworkManager.

As workaround, we are using NetworkManager for query.

The better approach should be:
 * Nispor query kernel netlink information of ipoib.
 * Use sysfs as fallback in case the running kernel does not has bug fixed. And this should be done by nispor also.

**Comment by ffmancera** [comment]
This is already done. IP over Infiniband configuration is been queried using nispor.
