### ISSUE TITLE
Outdated comment in specfile or missing Recommends

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1378]
https://github.com/nmstate/nmstate/blob/2a1632f3f8e8ad4a04721254ebbe9751596c5d16/packaging/nmstate.spec#L44
The specfile mentions that recommends is used but it is not. So the comment needs to be adjusted or the Requires added.

**Comment by shreyagupta30** [comment]
Hi, @ffmancera ! I am an outreachy applicant. I would love to contribute to this project. Can I take up this issue?

**Comment by ffmancera** [comment]
> Hi, @ffmancera ! I am an outreachy applicant. I would love to contribute to this project. Can I take up this issue?

Hello! Sorry but someone is already working on it in #1385
