### ISSUE TITLE
RFE: Use same terms for API and command-line utility

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1388]
Currently `nmstatectl set` calls `libnmstate.apply`. It would be nice to use the same terms for same features. Not sure if there are other instances that could be adjusted, too.

**Comment by ffmancera** [comment]
This will be a breaking change. I suggest to deprecate it first. IMO, we should adjust it on nmstatectl instead of libnmstate. What do you think?

**Comment by tyll** [comment]
yes, sounds good to me. Adjustin git on nmsatectl makes sense and it can use set as an alias for apply.

**Comment by ffmancera** [comment]
I've been thinking on that. IMO, we should do this before releasing 1.0.0. I am creating a `1.0.0 must` label.

**Comment by cathay4t** [comment]
create an alias from `apply` to `set`.
