### ISSUE TITLE
Maybe we don't need `NetworkManagerPlugin.refresh_content()` any more

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1398]
We are using nispor for 99% query data, please check whether we still need to refresh content of `NM.Client`.

**Comment by cathay4t** [comment]
Meanwhile, if mainloop does not add too much performance degrade, maybe we can also switch back to mainloop where we may share code with network-role.

**Comment by cathay4t** [comment]
@ffmancera Could you take a look on this with low priority? This helps you understand current complex NM MainContext code.

**Comment by ffmancera** [comment]
Yes, I will. Thanks!
