### ISSUE TITLE
Replace existing reference to "master" in stale bot

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#1399]
https://github.com/nmstate/nmstate/blob/dbb712e53220768b01ffee2c121aa2679191aabe/.github/stale.yml#L11

This link must be replace with the correct one pointing to base branch instead of master branch.

**Comment by 96RadhikaJadhav** [comment]
@ffmancera Could you please assign this issue to me?

**Comment by ffmancera** [comment]
> @ffmancera Could you please assign this issue to me?

Hi, there is someone already working on this.
