### ISSUE TITLE
`nmstatectl show` should support fnmatch syntax

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#1532]
## Describe the bug
nmstatectl show --help does not mention for interfaces that it uses fnmatch pattersn

## Nmstate version
0.3.6

## How reproducible
101%

## Steps to Reproduce
nmstatectl show --help

## Nmstate output
- Expected output:

should mention special fnmatch behavior

- Current output:

### Additional context
The behavior might be surprising when using meta characters for fnmatch, for example:

```
ip link add dummy[0] type dummy
nmstatectl show 'dummy[0]`  # this means dummy0
nmstatectl show 'dummy[[]0[]]'  # this means dummy[0]
```

Maybe include the table and the explanation from
https://docs.python.org/3/library/fnmatch.html
in the help:

"For a literal match, wrap the meta-characters in brackets. For example, '[?]' matches the character '?'."

**Comment by Aaryakhandelwal** [comment]
Hi, I wanted to proceed with this issue

**Comment by ffmancera** [comment]
Done! Enjoy the hacking! :)

**Comment by cathay4t** [comment]
The nmstatectl in rust does not support `fnatch` any more.

@Aaryakhandelwal Do you still want to work on expanding nmstatectl rust to support cases mentioned by tyll ?

**Comment by Aaryakhandelwal** [comment]
I wasn't aware of this. I will look for another issue then.

**Comment by tyll** [comment]
no longer relevant
