### ISSUE TITLE
Bug report: GenerateConfiguration C binding is not included with the latest nmstate-devel CentOS8 RPM

### ISSUE THREAD

**Issue by nmagnezi** [nmstate/nmstate#1914]
## Describe the bug
I tried to use the `GenerateConfiguration` Go binding, added with https://github.com/nmstate/nmstate/commit/dc2f69d8e55ec840b25f8646ded03d1ad33521d6, and it seems to be missing from the RPM.

Looking at the deployed [nmstate.h](https://gist.github.com/nmagnezi/8279f996e69f68dc6702870c3672f974) - and it is not there.

## Nmstate version
```
nmstate-devel-1.3.0-0.alpha.20220505.el8.x86_64
nmstate-1.3.0-0.alpha.20220505.el8.x86_64
python3-libnmstate-1.3.0-0.alpha.20220505.el8.noarch
nmstate-libs-1.3.0-0.alpha.20220505.el8.x86_64
```

## Platform
- Platform: CentOS 8

## How reproducible
- 100%

## Steps to Reproduce
1. Deploy

```go
package main

import (
	"fmt"
	"github.com/nmstate/nmstate/rust/src/go/nmstate"
)

func main() {
	nm := nmstate.New()
	test := `{
"interfaces": [{
  "name": "dummy1",
  "state": "up",
  "type": "dummy"
}]}
`
	var out string
	var err error

	out, err = nm.GenerateConfiguration(test)
	if err != nil {
		fmt.Printf("got error: %s", err.Error())
	}
	fmt.Printf(out)
}
```

## Nmstate output
- Expected output:
a valid config.

- Current output:
```go
../vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/nmstate.go:220:8: could not determine kind of name for C.nmstate_generate_configurations
```

**Comment by nmagnezi** [comment]
@ffmancera thank you for https://github.com/nmstate/nmstate/pull/1919.
When will we have a release (in a form of RPM) that includes it?

**Comment by ffmancera** [comment]
This was already fixed. Closing it, thanks for reporting!
