### ISSUE TITLE
The CI is randomly failing on VLAN or MTU tests.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#196]
Need investigate.

**Comment by tyll** [comment]
Since CentOS releases 7.6 recently, the packages in the docker image are now updated to newer versions, for example for NetworkManager. Maybe this is related.

**Comment by tyll** [comment]
vlan issues are addressed in #216

**Comment by tyll** [comment]
@EdDev recent error in the MTU tests: https://jenkins.ovirt.org/blue/organizations/jenkins/nmstate_nmstate_standard-check-pr/detail/nmstate_nmstate_standard-check-pr/880/pipeline

Seems to be sleeping to short until rollback is finished.

**Comment by tyll** [comment]
@cathay4t IMHO this is done, please open a new issue if there are more specific issues that need to be fixed.
