### ISSUE TITLE
YAML file with NonBreakingSpace characters renders wrong configuration

### ISSUE THREAD

**Issue by javipolo** [nmstate/nmstate#2051]
## Describe the bug
When a YAML file contains Non-Breaking space characters nmstate seems unable to properly parse the YAML content and renders a configuration that does not match the YAML definition

## Nmstate version
Tested on multiple versions
- 1.2.1
- 1.3.3
- 2.1.2

Examples are produced with 2.1.2 version, since output is more compact, but a fix for older python versions would also be needed O:)

## NetworkManager version
Not relevant

## Platform
Not relevant

## How reproducible
100%

### Create nmstate.yaml file with NonBreaking Spaces:
```
$ cat << EOF | xxd -r > nmstate.yaml
00000000: 696e 7465 7266 6163 6573 3a0d 0a2d 206e  interfaces:..- n
00000010: 616d 653a 2065 7468 300d 0ac2 a020 7479  ame: eth0.... ty
00000020: 7065 3a20 6574 6865 726e 6574 0d0a c2a0  pe: ethernet....
00000030: 2073 7461 7465 3a20 7570 0d0a c2a0 2069   state: up.... i
00000040: 7076 343a 0d0a c2a0 20c2 a020 656e 6162  pv4:.... .. enab
00000050: 6c65 643a 2074 7275 650d 0ac2 a020 c2a0  led: true.... ..
00000060: 2061 6464 7265 7373 3a0d 0ac2 a020 c2a0   address:.... ..
00000070: 202d 2069 703a 2031 3932 2e31 3638 2e31   - ip: 192.168.1
00000080: 3232 2e32 3530 0d0a c2a0 20c2 a020 c2a0  22.250.... .. ..
00000090: 2070 7265 6669 782d 6c65 6e67 7468 3a20   prefix-length: 
000000a0: 3234 0d0a                                24..
EOF
```

### Check the contents of the file
```
$ cat nmstate.yaml 
interfaces:
- name: eth0
  type: ethernet
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 192.168.122.250
      prefix-length: 24
```

### Generate network configuration (note that the IP address is missing from the generated configuration)
```
$ nmstatectl gc nmstate.yaml
[2022-09-30T16:27:45Z WARN  nmstate::ifaces::inter_ifaces] Setting unknown type interface eth0 to ethernet
[2022-09-30T16:27:45Z INFO  nmstate::ifaces::inter_ifaces] Adding interface eth0 with type ethernet, up priority 0
---
NetworkManager:
  - - eth0.nmconnection
    - "[connection]\nautoconnect=true\nautoconnect-slaves=-1\nid=eth0\ninterface-name=eth0\ntype=802-3-ethernet\nuuid=dfd202f5-562f-5f07-8f2a-a7717756fb70\n\n[ipv4]\nmethod=disabled\n\n[ipv6]\nmethod=disabled\n"
```

### Expected output:
On of the two would be good:
- Output an error stating that the supplied YAML is invalid
- Renders proper configuration files

#### Fix the previous yaml
```
$ sed -i 's/\xC2\xA0/ /g' nmstate.yaml
```

#### Check that at the naked eye the configuration looks exactly the same as before
```
$ cat nmstate.yaml 
interfaces:
- name: eth0
  type: ethernet
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 192.168.122.250
      prefix-length: 24
```

#### Generate network configuration (note that now IP address is defined)
```
$ nmstatectl gc ~/tmp/nmstate.yaml 
[2022-09-30T16:25:50Z INFO  nmstate::ifaces::inter_ifaces] Adding interface eth0 with type ethernet, up priority 0
---
NetworkManager:
  - - eth0.nmconnection
    - "[connection]\nautoconnect=true\nautoconnect-slaves=-1\nid=eth0\ninterface-name=eth0\ntype=802-3-ethernet\nuuid=dfd202f5-562f-5f07-8f2a-a7717756fb70\n\n[ipv4]\naddress0=192.168.122.250/24\nmethod=manual\n\n[ipv6]\nmethod=disabled\n"
```

**Comment by cathay4t** [comment]
Normally, I would ask user to polish the yaml file before sending to nmstatectl, but anyway, issue is fixed by https://github.com/nmstate/nmstate/pull/2058

Thanks for the bug report!

I have to point out again: the CLI is a not an API but a developer/admin tool.
The C API is based on json, the Rust API is based on `struct`, none of them has this kind of problem.

**Comment by cathay4t** [comment]
I took a second look on this issue. This might be a bug or feature of yaml. In both rust and python, above yaml are handled as:


```json
{
 "interfaces": [
  {
   "name": "eth0"
  }
 ],
 "\u00a0 type": "ethernet",
 "\u00a0 state": "up",
 "\u00a0 ipv4": null,
 "\u00a0 \u00a0 enabled": true,
 "\u00a0 \u00a0 address": null,
 "\u00a0 \u00a0 - ip": "192.168.122.250",
 "\u00a0 \u00a0 \u00a0 prefix-length": 24
}
```

which lead to the ipv4 disable problem like above.

This reveal a nmstate API problem: Not complaining about invalid key at top level. Will fix soon.

**Comment by cathay4t** [comment]
https://github.com/nmstate/nmstate/pull/2059 is fixing the invalid top level key/type.

Without auto-clean patch  in CLI, user will get error with above cooked yaml:

```
serde_yaml::Error: Unsupported keys found: ["\u{a0} ipv4", "\u{a0} state", "\u{a0} type", "\u{a0} \u{a0} - ip", "\u{a0} \u{a0} address", "\u{a0} \u{a0} enabled", "\u{a0} \u{a0} \u{a0} prefix-length"]
```
