### ISSUE TITLE
No support for ip rule suppressors in route-rules

### ISSUE THREAD

**Issue by larsks** [nmstate/nmstate#2114]
## Describe the bug

The `route-rules` section of an nmstate configuration does not support the full suite of policy routing commands. In particular, it lacks support for suppressors such as `suppress_prefixlen`, without which it is difficult to create fairly typical configurations.

For example, I would like to add a source route so that replies to requests coming in on a particular interface also go out the same interface. Assuming that I have two interfaces named INT and EXT, like this:

```
8: INT: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 52:54:00:d1:d1:85 brd ff:ff:ff:ff:ff:ff
    inet 192.168.89.63/24 brd 192.168.89.255 scope global dynamic noprefixroute INT
       valid_lft 2730sec preferred_lft 2730sec
    inet6 fe80::5054:ff:fed1:d185/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

3: EXT: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:d2:a5:97 brd ff:ff:ff:ff:ff:ff
    inet 100.64.0.108/24 brd 100.64.0.255 scope global dynamic noprefixroute EXT
       valid_lft 2542sec preferred_lft 2542sec
    inet6 fe80::5054:ff:fed2:a597/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

And a `main` routing table like this:

```
default via 192.168.89.1 dev INT proto dhcp src 192.168.89.63 metric 48
10.128.0.0/23 dev ovn-k8s-mp0 proto kernel scope link src 10.128.0.2
10.128.0.0/14 via 10.128.0.1 dev ovn-k8s-mp0
100.64.0.0/24 dev EXT proto kernel scope link src 100.64.0.108 metric 102
169.254.169.0/30 via 192.168.89.1 dev INT
169.254.169.3 via 10.128.0.1 dev ovn-k8s-mp0
172.30.0.0/16 via 192.168.89.1 dev INT mtu 1400
192.168.89.0/24 dev INT proto kernel scope link src 192.168.89.63 metric 48
```

I need rules like this:

```
ip rule add priority 200 from 100.64.0.0/24 table main suppress_prefixlen 0
ip rule add priority 210 from 100.64.0.0/24 table 200
ip route add table 200 default via 100.64.0.1 dev EXT
```

That first rule with the `suppress_prefixlen 0` allows us to consume non-default routes from the `main` routing table; without that, we would not be able to reach any of the networks that are accessible only via INT when using a source address on the 100.64.0.0/24 network.

## Nmstate version

I haven't the foggiest, but I'm consuming nmstate via the openshift nmstate operator, `kubernetes-nmstate-operator.4.11.0-202210262118`.

## NetworkManager version

`NetworkManager-1.36.0-9.el8_6.x86_64`

## Platform

Red Hat CoreOS 4.11 (411.86.202210311708-0) (aka RHEL 8.6)

## How reproducible

100%

**Comment by cathay4t** [comment]
I have created PR https://github.com/nmstate/nmstate/pull/2391 for this feature.

We are moving 1.4 branch into maintenance mode for bug fix only. Please try to use Red Hat CoreOS 4.13 or later which ships nmstate 2.x branch.
