### ISSUE TITLE
Links for badges in README.md link to images instead of status page

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#2139]
The CI badge links to https://github.com/nmstate/nmstate/workflows/CI/badge.svg?branch=base but it should link to a web page that shows the results of the CI runs against the base branch. The crates and docs badge also link to the image instead of a useful web page. Also, there seems to be some markdown error resulting in brackets (`[`) being shown.

**Comment by 0xyshv** [comment]
@ffmancera 
I would like to work on this, could you please assign it to me?

**Comment by jona42-ui** [comment]
hello @tyll  or @cathay4t  you can assign me this issue as its now work in progress
