### ISSUE TITLE
Code refers to preferred/valid "left", instead of "lifetime" - also in YAML

### ISSUE THREAD

**Issue by jiphex** [nmstate/nmstate#2357]
This is in a few places, including [here](https://github.com/nmstate/nmstate/blob/e73b147f5ff469007303d1892a5337bb3fee10bd/rust/src/lib/ip.rs#L896), however "lft" is an abbreviation for "lifetime" (see RFC8415, RFC4861 etc) - it may be confusing if it's referred to as "preferred left" in the YAML.

**Comment by ffmancera** [comment]
+1

**Comment by cathay4t** [comment]
Since those options are query only, it is OK to change rust API for this case.
