### ISSUE TITLE
RFE: Allow setting DNS options

### ISSUE THREAD

**Issue by myllynen** [nmstate/nmstate#2360]
Currently, it is possible to configure DNS servers and search domains but not DNS options. It could be helpful to allow setting options such as no-aaaa when disabling IPv6 otherwise as well. Thanks.

**Comment by cathay4t** [comment]
Thanks for reaching out! Let me do that in this month!

**Comment by myllynen** [comment]
I noticed that instead of configuring DNS servers / search domains / options in connection files one could create a configuration file in NM's `conf.d` directory with something like this:

```
[global-dns-domain-*]
servers=1.1.1.1,8.8.8.8 
[global-dns]
searches=example.com,domain.name
options=edns0,no-aaaa,rotate
```

While the end result is the same on a freshly booted up system the benefit of having these configurations in a global configuration instead of a connection profile configuration file is that changes for the former will be applied after reloading NetworkManager while the latter requires restarting NetworkManager.

Reloading should have lesser impact on live systems than restarting so it might be a good idea to prefer that alternative.

**Comment by cathay4t** [comment]
Thanks for the update on the workaround!

I have planned to do this in these two weeks using programmable way using NetworkManager API.

**Comment by cathay4t** [comment]
Sorry for the late. PR #2407  is waiting for review.
