### ISSUE TITLE
Add LLDP TX Support

### ISSUE THREAD

**Issue by camrossi** [nmstate/nmstate#2386]
I have enabled LLDP support via NMState on OpenShift 4.12.19 with this configuration

```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ocp-sr-iov-bm02-lldp
spec:
  nodeSelector:
    kubernetes.io/hostname: "ocp-sr-iov-bm02.ocp-sr-iov.cam.ciscolabs.com"
  desiredState:
    interfaces:
      - name: eno7
        description: eno7
        type: ethernet
        lldp:
          enabled: true
```
This works fine and I am learning my neighbours but apparently NMState is only working in RX and if I issue a show lldp neighbors on my switches the nodes are not visible. 

I have confirmed this with a sniffer trace and as you can see we receive LLDP packets but don't send any
```
sh-4.4# tcpdump -i eno7 ether proto 0x88cc
listening on eno7, link-type EN10MB (Ethernet), capture size 262144 bytes
05:22:20.856152 LLDP, length 470: Leaf204
05:22:50.857990 LLDP, length 470: Leaf204
05:23:20.858980 LLDP, length 470: Leaf204
05:23:50.860028 LLDP, length 470: Leaf204
05:24:20.862027 LLDP, length 470: Leaf204
05:24:50.863353 LLDP, length 470: Leaf204
05:25:20.864316 LLDP, length 470: Leaf204
```

I was expecting enabling LLDP would also make the host transmit the LLDP packets.
I enabled LLDP primary to be able so use the show lldp neighbours command on my switches. 

Also I am a bit confused on this section in the LLDP documentation: https://nmstate.io/features/lldp.html#simulate-a-lldp-package
What does this mean ?

**Comment by cathay4t** [comment]
@camrossi Nmstate or its backend NetworkManager does not support sending out LLDP packages, you need a dedicate daemon(e.g, [lldpd][1]).

The example you found is purely for our test purpose, it just resend a stored network package sent from a LLDP enabled switch, so we can test our LLDP receiving functionally in nmstate and NetworkManager.


[1]: https://github.com/lldpd/lldpd

**Comment by camrossi** [comment]
I was suspecting that but wanted to be sure it is not something we can fix from NMState... 
I will check with RedHat if there is an option to run lldpd on CoreOS

Thanks!
