### ISSUE TITLE
Use workspace dependency

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2406]
https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table

**Comment by saleha-zf** [comment]
Hello @cathay4t can you tell a little more about this issue?

**Comment by cathay4t** [comment]
Currently we have rust crate dependency defined in `rust/src/lib/Cargo.toml`, `rust/src/cli/Cargo.toml` and etc.

The better way is unify the dependency to workspace level `rust/Cargo.toml` and refer it crates.
Above link has explained how to do it.

**Comment by Bethel-Iyke** [comment]
Please i would like to work on this issue in relation to python workspace dependencies. please can i go ahead

**Comment by cathay4t** [comment]
Assigned.

**Comment by cathay4t** [comment]
To test whether your changes works, please use `cd rust; cargo build`.
