### ISSUE TITLE
Promoting  liangwen12year as maintainer of nmstate

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2484]
@liangwen12year  has contributed a lot to nmstate project, including but not limited to:
 * PR reviews.
 * Features
    *  https://github.com/nmstate/nmstate/pull/2453
    * https://github.com/nmstate/nmstate/pull/2418
 * CI fixes:
   * https://github.com/nmstate/nmstate/pull/2471
   * https://github.com/nmstate/nmstate/pull/2465
 * Many bug fixes. 
 
Hereby, I would like to propose promoting @liangwen12year as maintainer of nmstate with admin right.

Please provide your vote or comments before end of 2023.

**Comment by cathay4t** [comment]
@ffmancera @EdDev @tyll @qinqon @bengal

**Comment by qinqon** [comment]
> @ffmancera @EdDev @tyll @qinqon @bengal

Fine by me, impressive work! thanks @liangwen12year

**Comment by EdDev** [comment]
+1
I'm no longer an active contributor, but I am glad to support your proposal.

Great work!

**Comment by ffmancera** [comment]
+1

Great work!

**Comment by cathay4t** [comment]
Invite sent. Thanks for the votes!

Closing

**Comment by tyll** [comment]
Congratulations! It seems that @liangwen12year needs to be added to CODEOWNERS.
