### ISSUE TITLE
Typo when hiding passswords

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#2494]
Instead of `hid` it should be `hidden` here:

https://github.com/nmstate/nmstate/blame/0762aa8660ba3d6fa2b7b538cf6550047d75b96d/rust/src/python/libnmstate/state.py#L23

Since it is also used for other items than passwords, it might also be good to rename this to `secret_hidden_by_nmstate`

**Comment by cathay4t** [comment]
If we changed that, previous stored YAML state will not works as expected. It is part of our API now, cannot change.

**Comment by tyll** [comment]
This is unfortunate.

**Comment by cathay4t** [comment]
Sorry for my bad English.
