### ISSUE TITLE
Create alias for nmstaetctl subcommand

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2579]
Considering these two subcommand are widely used by developer and user, to save some typing, we can create alias like:

 * `nmstatectl a` == `nmstatectl apply`
 * `nmstatectl s` == `nmstatectl show`

This is not about bash autocomplet, but rust clap alias.

**Comment by abhishek23tiwari** [comment]
Hi, Can I work on this?

**Comment by saleha-zf** [comment]
Hello, is this yet to be assigned? i would love to work on this

**Comment by cathay4t** [comment]
Sure. Please go ahead and create PR for this. It should be a very simple task.

**Comment by faraiayokunle** [comment]
use clap::{App, Arg, SubCommand};

fn main() {
    let matches = App::new("nmstatectl")
        .subcommand(SubCommand::with_name("apply").alias("a"))
        .subcommand(SubCommand::with_name("show").alias("s"))
        .get_matches();

    match matches.subcommand_name() {
        Some("apply") | Some("a") => {
            // Handle apply logic
            println!("Applying settings...");
        }
        Some("show") | Some("s") => {
            // Handle show logic
            println!("Showing settings...");
        }
        _ => println!("Invalid subcommand"),
    }
}

**Comment by faraiayokunle** [comment]
> Sure. Please go ahead and create PR for this. It should be a very simple task.

@cathay4t I'll like to Make contributions to this task too.

**Comment by faraiayokunle** [comment]
use clap::{App, Arg, SubCommand};

fn main() {
    let matches = App::new("nmstatectl")
        .subcommand(SubCommand::with_name("apply").alias("a"))
        .subcommand(SubCommand::with_name("show").alias("s"))
        .get_matches();

    match matches.subcommand_name() {
        Some("apply") | Some("a") => {
            // Handle apply logic
            println!("Applying settings...");
        }
        Some("show") | Some("s") => {
            // Handle show logic
            println!("Showing settings...");
        }
        _ => println!("Invalid subcommand"),
    }
}
