### ISSUE TITLE
Use `nispor::NetState::retrieve_with_filter_async`

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2580]
As first step to providing async API in nmstate, we should use `nispor::NetState::retrieve_with_filter_async()` instead of `nispor::NetState::retrieve_with_filter()`.

**Comment by EjiroLaurelD** [comment]
> As first step to providing async API in nmstate, we should use `nispor::NetState::retrieve_with_filter_async()` instead of `nispor::NetState::retrieve_with_filter()`.

Hello, my name is Ejiro, an outreachy applicant. Can I work on this?

**Comment by cathay4t** [comment]
Assigned.

**Comment by cathay4t** [comment]
This has been fixed by https://github.com/nmstate/nmstate/pull/2676
