### ISSUE TITLE
Hide secrets in `Debug` trait of `NetworkState` and its subtypes

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2587]
We have `NetworkState.hide_secrets()` which will replace secrets(like password) to `<_password_hid_by_nmstate>`. 

Please create implementation of `std::fmt::Debug` trait for `NetworkState`(and its subtypes), make sure
we do not print password when user do `println!("{:?}", net_state)`.

If any data type holds no secrets, you can use default derive of Debug.

**Comment by faraiayokunle** [comment]
@cathay4t I'll like to work on this. Thank you.

**Comment by maha-sachin** [comment]
@cathay4t  I am Maha from outreachy,  If @faraiayokunle becomes unavailable, could you please consider assigning me to this issue? I'm keen to contribute and would be happy to take on the task.
