### ISSUE TITLE
Deprecate `PrettyState` in python API

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2588]
The `PrettyState` is only used for test codes.

1. Mark `PrettyState` as deprecated in Python API, providing message indicate `libnmstate.show()` output is already sorted.
2. Remove test cases regarding `PrettyState`

**Comment by jona42-ui** [comment]
hi @cathay4t  kindly 
 assign me this to avoid duplication

**Comment by ffmancera** [comment]
Fixed!

**Comment by jona42-ui** [comment]
thanks too 
i need another task @cathay4t @ffmancera
