### ISSUE TITLE
Use `SPDX-License-Identifier` to all rust and python API code

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2589]
All rust code should have `// SPDX-License-Identifier: Apache-2.0` as first line.

All python code should have `# SPDX-License-Identifier: LGPL-2.1-or-later` as first line.

Meanwhile, please introduce a CI task for this, you may take a look on https://github.com/apache/skywalking-eyes for github action.

**Comment by saleha-zf** [comment]
I'd like to work on this, can i be assigned this? thankyou

**Comment by ffmancera** [comment]
Assigned!
