### ISSUE TITLE
Documentation for Rust is not mention in README

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#2593]
In the documentation section at https://github.com/nmstate/nmstate/blob/base/README.md#documentation the Rust crate documentation is missing. We should add it.

You can find the rust crate docs here: https://docs.rs/nmstate/latest/nmstate/index.html

**Comment by KimFarida** [comment]
Please can I be assigned this issue?
I think I'm interested in exploring this please @ffmancera

**Comment by Ytemiloluwa** [comment]
I will like to work on this @ffmancera

**Comment by ffmancera** [comment]
@Ytemiloluwa sorry, @KimFarida was first. I will create another issue for you and ping you there. I hope that is fine :)

**Comment by Ytemiloluwa** [comment]
> @Ytemiloluwa sorry, @KimFarida was first. I will create another issue for you and ping you there. I hope that is fine :)

okay that is fine by me. @ffmancera

**Comment by anshikavashistha** [comment]
@ffmancera please assign it to me
