### ISSUE TITLE
Add compilation and instalations steps in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#2594]
How to compile and install Nmstate locally is not described properly. It should be described in a new section in CONTRIBUTING.md

https://github.com/nmstate/nmstate/blob/base/CONTRIBUTING.md

**Comment by beekaz** [comment]
Hello  @ffmancera, please can you assign me this to me

**Comment by daud99** [comment]
hello @ffmancera, Kindly assign it to either beekaz or me. Thanks

**Comment by Ytemiloluwa** [comment]
Hello @ffmancera can you assign this issue to me please.

**Comment by Precious000** [comment]
Hi there!
I’ll like to work on this project if you don’t mind. Thanks

**Comment by ffmancera** [comment]
Hi! As discussed on nmstate matrix channel this issue was going to be assigned to @Ytemiloluwa. Sorry for the inconvenience.

**Comment by Ytemiloluwa** [comment]
> Hi! As discussed on nmstate matrix channel this issue was going to be assigned to @Ytemiloluwa. Sorry for the inconvenience.

Thank you @ffmancera

**Comment by Ytemiloluwa** [comment]
Hello @ffmancera will the compilation and installation steps be for all platforms? 
i.e
- Linux (Fedora)
- macOS 
- Windows

**Comment by ffmancera** [comment]
> Hello @ffmancera will the compilation and installation steps be for all platforms? i.e
> 
>     * Linux (Fedora)
> 
>     * macOS
> 
>     * Windows

Nmstate is only supported in Linux, so only Linux is required.

**Comment by maha-sachin** [comment]
@ffmancera Hi I am Maha from Outreachy, can you assign me any new issues if available?
