### ISSUE TITLE
lldp nmconnection incorrectly written as lldp=false when it should be lldp=0

### ISSUE THREAD

**Issue by oybed** [nmstate/nmstate#2743]
## Describe the bug
The nmconnection output writes `lldp=false` instead of using an `int32` value - this causes the NetworkManager to throw a warning and won't modify the LLDP parameter for an interface. 

## Nmstate version
- 2.2.33

## NetworkManager version
- 1.46.0

## Platform
- RHEL 9 / CoreOS 4.16

## How reproducible
- Set lldp enable to false in nmstate config

## Steps to Reproduce
Test yaml to disable `lldp`:
```
    interfaces:
    - name: ens2f1
      type: ethernet 
      state: up
      lldp:
        enabled: false
```
Then run `nmstatectl gc` to see the lldp=false output, i.e.:

```
> nmstatectl gc test-lldp.yaml 
[2024-07-29T16:18:56Z INFO  nmstatectl] Nmstate version: 2.2.33
NetworkManager:
- - ens2f1.nmconnection
  - |
    [connection]
    autoconnect=true
    autoconnect-slaves=-1
    id=ens2f1
    interface-name=ens2f1
    lldp=false <<< this is invalid
    type=802-3-ethernet
 <output truncated>
```

## Nmstate output
- Expected output:
The nmconnection configuration should be an integer, e.g.:
lldp=0 

- Current output:
lldp=false

### Additional context
From the docs [1]:
![image](https://github.com/user-attachments/assets/9155faf0-772e-4ccb-954f-29324acf3230)

\[1\]: https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/nm-settings-nmcli.html

**Comment by ihuguet** [comment]
It is correct from nmstate point of view to show and accept lldp as true/false. An nmstate user shouldn't need to know specific things of NetworkManager. For an nmstate user, the intuitive thing is to use true/false to enable/disable or, in any case, not to specify lldp to keep it unchanged.

Internally, nmstate converts to/from the types that NetworkManager needs.

What's the warning that you see? It is true that nmstate sends the value as D-Bus BOOLEAN type (see [here](https://github.com/nmstate/nmstate/blob/base/rust/src/lib/nm/nm_dbus/connection/conn.rs#L393)), but I have tested it and my NetworkManager doesn't complain and changes it correctly.

(note: I'm going to send a PR fixing the line I have linked, but I'm still curious what warning do you see).

**Comment by oybed** [comment]
@ihuguet thank you for the information, and yes, using true/false on the "input" side to nmstate is perfectly fine - it's the nmconnection configuration written out that is wrong. Looks like your PR may take care of this though, so that's great. 

Apologize for not including a screenshot of the warning. I have done so below (from a system with 8 NICs == 8 warnings). Note that the outcome of this warning is that lldp is not configured the way I'm expecting it to do be (i.e.: disabled) , so the warning in this case is really an error as it continues on with the default value (i.e.: enabled). 

![image](https://github.com/user-attachments/assets/03b43f91-7b07-4c35-97cf-cfdd15e97db0)
