### ISSUE TITLE
Simplfy and unify the unit test in run-test.sh and tox.ini

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#285]
Thank you. I see. If we can assume that nmstate will be installed only for one python version in one running container, it seems that this can be simplified using a shell glob (does not need `PYTHON_SITE_PATH_CMD` anymore):

```
diff --git a/automation/run-tests.sh b/automation/run-tests.sh
index f6a1cf0..8164f12 100755
--- a/automation/run-tests.sh
+++ b/automation/run-tests.sh
@@ -95,8 +95,8 @@ function run_tests {
             --log-date-format='%Y-%m-%d %H:%M:%S' \
             --log-format='%(asctime)s %(filename)s:%(lineno)d %(levelname)s %(message)s' \
             --durations=5 \
-            --cov=\$($PYTHON_SITE_PATH_CMD)/libnmstate \
-            --cov=\$($PYTHON_SITE_PATH_CMD)/nmstatectl \
+            --cov /usr/lib/python*/site-packages/libnmstate \
+            --cov /usr/lib/python*/site-packages/nmstatectl \
             --cov-report=html:htmlcov-integ \
             --cov-report=term \
             tests/integration \
```
And this might also again allow to move this into tox.ini (there are currently only outdated integration test environments that should probably be removed).

_Originally posted by @tyll in https://github.com/nmstate/nmstate/pull/233_

**Comment by EdDev** [comment]
If this is still relevant, please open it through [Jira could](https://nmstate.atlassian.net/secure/RapidBoard.jspa?projectKey=NMSTATE).

**Comment by tyll** [comment]
The `PYTHON_SITE_PATH_CMD` variable is already removed: https://github.com/nmstate/nmstate/blob/master/automation/run-tests.sh#L134

There is also a Jira card open to cleanup tox.ini.

**Comment by ffmancera** [comment]
Could we close this now? Thanks @tyll
