### ISSUE TITLE
Replacing mainloop with GLib.MainContext.iteration()

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#362]
Inside the mainloop we cannot raise.
The mainloop needs to be gracefully terminated, otherwise only the timeout will end it (and in a non graceful manner).

Perhaps investigating exceptions inside the mainloop is to be investigated further, we should consider it.

_Originally posted by @EdDev in https://github.com/nmstate/nmstate/pull/332_

**Comment by EdDev** [comment]
The project is managing issue through Jira could, please open this on Jira and close this one.

There seem to be no way to do this directly, but we could wrap it nicely on the action execution.

**Comment by cathay4t** [comment]
Replacing mainloop with `GLib.MainContext.iteration()` could helps.

**Comment by cathay4t** [comment]
Using `GLib.MainContext.iteration()` could give use features like:
 * More control on timeout.
 * Could raise exception.
 * Could activate all profiles simultaneously.

This has been evaluated in https://github.com/cathay4t/nmstate/tree/plugin
