### ISSUE TITLE
report network state and change status from netapplier.apply()

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#39]
For the Ansible module and possible other consumers it would be great for `netapplier.apply()` to report back the state after applying the supplied (partial) state and whether this changed anything in the state.

**Comment by tyll** [comment]
An idea would be to return a dictionary `{'state': ..., 'changed': True|False}`

**Comment by EdDev** [comment]
I like this one.
Not sure if there is a need to return the current new state, but we could add it as an option.
post_apply_state = {}
apply(desired_state, current_state_outcome=post_apply_state)

**Comment by tyll** [comment]
Another idea from @EdDev was to use a transaction object:

```
t = nmstate.transaction()
t.apply(...)
assert t.has_changed
new_state = t.outcome_state()
```

**Comment by tyll** [comment]
Moved to https://nmstate.atlassian.net/browse/NMSTATE-294
