### ISSUE TITLE
Cannot use run-test.sh on Fedora 30.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#420]
The `docker_exec 'cd /workspace/nmstate && cp -rf /workspace/nmstate /tmp/'` will return 129 due to the bug of https://github.com/docker/compose/issues/3379

To fix that, comment out `test -t 1 && USE_TTY="-t"` will solve it.

**Comment by cathay4t** [comment]
@EdDev Can we just remove the `test -t 1 && USE_TTY="-t"` line ?

**Comment by EdDev** [comment]
If we remove `USE_TTY`, then we will not see the container output on the console/log. Or do I miss something here?

What exactly behaves differently in Fedora 30 compared to 28/29/CentOS7?

**Comment by cathay4t** [comment]
> If we remove `USE_TTY`, then we will not see the container output on the console/log. Or do I miss something here?

Without, I just lose color of pytest, nothing else changed.

> 
> What exactly behaves differently in Fedora 30 compared to 28/29/CentOS7?

No idea, both EL7 and F30 are using docker-1.13.1. But F30 return 129 for `cp -rf` command.

I will try another workaround for chaging `bash to sh`.

**Comment by cathay4t** [comment]
changing `bash to sh` does not solve this problem.

**Comment by cathay4t** [comment]
The Fedora 29 works well even it has identical docker version like F30 did.

**Comment by EdDev** [comment]
How about just migrating to *podman*?
I use it for the unit tests and it works great.

Fixing the docker network dependency should be easy.

**Comment by cathay4t** [comment]
After update of Fedora 29 on July 2, it has the same problem with F30 now. :(

**Comment by ffmancera** [comment]
Could we close this? @cathay4t
