### ISSUE TITLE
Support OVS bondning

### ISSUE THREAD

**Issue by phoracek** [nmstate/nmstate#506]
We have a user of https://github.com/nmstate/kubernetes-nmstate/ who would need to setup OVS bonding. I'm not sure whether there has been any effort on nmstate to support it. Would you please give me a heads-up? I recall there were some issues with port/interface abstractions. We would be happy to help implementing it and defining the API.

**Comment by phoracek** [comment]
@EdDev

**Comment by EdDev** [comment]
We have a basic implementation in place for OVS, but it does not include its bond option.
We plan to address ovs in the RHEL 8.2 cycle, mainly in terms of stability (it was unstable on CI) but also for OpenStack usability if we will have resources.

For bond support, we need first to adjust the current schema: https://github.com/nmstate/nmstate/blob/298801d88725674f329f8efc4dbfce9bfc49d7d6/libnmstate/schemas/operational-state.yaml#L244

You are welcome to suggest changes to the schema and help out with the implementation.

Please note that we are managing our work on upstream jira.

**Comment by phoracek** [comment]
@EdDev would you re-open this? OVS bonding API is not implemented. Is it?

**Comment by EdDev** [comment]
@tyll , thanks. Yes, it should not be closed.

**Comment by tyll** [comment]
It is now fixed by #795
