### ISSUE TITLE
Use a class for state in nmstate or rework generate_ifaces_metadata()

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#58]
`generate_ifaces_metadata()` seems to modify the parameters it gets but it should instead return what it changed. Other than from the name it is not cleat that this has side effects:

https://github.com/nmstate/nmstate/blob/d363cbba22d07e65bc9f243e4680123b8e8eca05/libnmstate/netapplier.py#L45

**Comment by ffmancera** [comment]
This has been solved by #1035 :-)
