### ISSUE TITLE
Cannot create ovs-bridge with a ovs-interface with same name as port

### ISSUE THREAD

**Issue by qinqon** [nmstate/nmstate#601]
The ovs-vsctl tool when used to create a bridge it adds the ovs-bridge ovs-port and ovs-interface in one go and ovs-bridge and ovs-interface with same name, also the ovs-cni expect the ovs-interface listed by netlink to have the same name as the ovs-bridge.

Configuring that with nmstate we get the following error:

```
NM main-loop aborted: Connection adding failed: error=nm-connection-error-quark: connection.master: A connection with a 'ovs-bridge' setting must not have a master. (7)
```

Tested at https://github.com/nmstate/nmstate/pull/600

**Comment by tyll** [comment]
Thank you, can you please report this in Jira?

**Comment by tyll** [comment]
This is now tracked in Jira:   https://nmstate.atlassian.net/browse/NMSTATE-286
