### ISSUE TITLE
nmstate fails when Infiniband interfaces are present

### ISSUE THREAD

**Issue by murashkin17** [nmstate/nmstate#655]
nmstate does not have Infiniband type implemented. It also requires MAC address to be 6 octets.

It breaks oVirt vdsm when a host has Infiniband interfaces ([Red Hat Bugzilla 1785800](https://bugzilla.redhat.com/show_bug.cgi?id=1785800)).

nmstate shall have Infiniband added or, at least, accept MAC addresses 20 octets in size.

Here is an example of Infiniband MAC address

```
6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UP group default qlen 256
    link/infiniband 80:00:02:08:fe:80:00:00:00:00:00:00:f4:52:14:03:00:8d:52:11 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
```

The patch below adds Infiniband MAC addresses support. It is, obviously, not a complete solution. But at least it makes vdsm happy. 

```
--- libnmstate/schemas/operational-state.yaml.orig 2019-12-12 09:24:22.000000000 -0600
+++ libnmstate/schemas/operational-state.yaml	2019-12-21 12:09:38.277135571 -0600
@@ -63,7 +63,7 @@
         - down
     mac-address:
       type: string
-      pattern: "^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$"
+      pattern: "^(([a-fA-F0-9]{2}:){5}|([a-fA-F0-9]{2}:){19})[a-fA-F0-9]{2}$"
     bridge-vlan-tag:
       type: integer
       minimum: 0
```

**Comment by murashkin17** [comment]
Applying the patch resolves some oVirt issues but not all of them as nmstate returns "unknown" interface type.

As the result, nmstate is unusable if oVirt vdsm host has Infiniband interfaces. The only way to run vdsm is to disable nmstate completely.

**Comment by ffmancera** [comment]
Hi, we have applied a patch to solve the schema problem. We are also going to work on supporting infiniband interfaces. Thanks! #653

**Comment by tyll** [comment]
@murashkin17 thank you for your report. Why is it a problem for vdsm if nmstate returns an "unknown" interface type. What is the actual error?

**Comment by murashkin17** [comment]
In the case of oVirt, events similar to one below are logged in the engine log

2019-12-21 13:14:23,022-06 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.HostSetupNetworksVDSCommand] (default task-125) [7c65ff99-7cbd-4247-b577-e9149862f141] Error: VDSGenericException: VDSErrorException: Failed to HostSetupNetworksVDS, error = Internal JSON-RPC error: {'reason': 'Unexpected failure of libnm when running the mainloop: run execution'}, code = -32603

Because of this error, the host network configuration cannot be changed via oVirt. We had to disable nmstate completely. 

For more details, including detailed oVirt log, see [Red Hat Bugzilla 1785800](https://bugzilla.redhat.com/show_bug.cgi?id=1785800#c7).

Here what nmstatectl show on the host returns (all fields are wrong except the MAC address - the interface is actually up, IPs are assigned, and its type is infiniband) 

- name: ib0
  type: unknown
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  mac-address: 80:00:02:08:FE:80:00:00:00:00:00:00:F4:52:14:03:00:8D:52:11
  mtu: 65520

**Comment by tyll** [comment]
@murashkin17 @EdDev is there something that needs to be fixed in Nmstate right now? Is Infiniband support needed in Nmstate? Then it should be a RFE IMHO.

**Comment by EdDev** [comment]
From my point if view, infiniband or any other type of interface existence, should not cause a failure. Configuring such interfaces is not supported and may fail.
This issue is about not failing if it exists.

@almusil , @murashkin17 , please help clarify the current status.

**Comment by tyll** [comment]
There is nothing we can do here since there is no clear request, therefore I will close this issue. A specific Infiniband request is logged in #1138.
