### ISSUE TITLE
Mainloop timeout when too many interfaces are defined in one transaction

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#727]
During oVirt/VDSM tests, 150+ vlans with bridges on top have been defined in one transaction, causing the mainloop global timeout to expire in the middle and therefore failing it.

There seems to be a need to increase the global mainloop timeout and introduce per-action timeout.

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1788081

**Comment by tyll** [comment]
Jira discussion: https://nmstate.atlassian.net/browse/NMSTATE-303
