### ISSUE TITLE
Drop nmstate-0.1 and Fedora 31 and earlier support

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#758]
- remove the nmstate-0.1 branch from Github
- remove the nmstate-0.1 related Copr repositories
- Remove Fedora 31 and earlier chroots (build targets) from Copr repositories

Do this on 17 February or later if there are no objections

**Comment by EdDev** [comment]
nmstate-0.1 is distributed in CentOS 8.1 therefore I do not understand how support can be dropped.

Removing the branch implies that history is erased. I do not think it is a valid action.

nmstate-0.2 is targeted towards CentOS 8.2 and Fedora 32. In the meantime it is tested and known to work with CentOS 8.1 that is patched with NetworkManager 1.22.
Users are left therefore with nmstate-0.1 if they want to use official distribution versions.

**Comment by tyll** [comment]
> nmstate-0.1 is distributed in CentOS 8.1 therefore I do not understand how support can be dropped.

It will continue to exist in CentOS 8.1 and Fedora 31. I understood that CentOS will not do any updates to nmstate within 8.1. If there is something extremely urgent, a patch can be backported downstream. This ticket is about upstream support, not downstream support.

> Removing the branch implies that history is erased. I do not think it is a valid action.

The tags still reference the commits and therefore they will not be lost. Only the bump commit to 0.1.4 could be garbage collected but it does not contain any useful information.

> nmstate-0.2 is targeted towards CentOS 8.2 and Fedora 32. In the meantime it is tested and known to work with CentOS 8.1 that is patched with NetworkManager 1.22.
> Users are left therefore with nmstate-0.1 if they want to use official distribution versions.

I am not sure what you are getting at, here.

**Comment by EdDev** [comment]
> > nmstate-0.1 is distributed in CentOS 8.1 therefore I do not understand how support can be dropped.
> 
> It will continue to exist in CentOS 8.1 and Fedora 31. I understood that CentOS will not do any updates to nmstate within 8.1. If there is something extremely urgent, a patch can be backported downstream. This ticket is about upstream support, not downstream support.

CentOS is considered upstream from a user point of view, it represent the community. From a code point of view, it is downstream because to comes from RHEL.
nmstate-0.1 on Fedora 31 is considered upstream, right? Like CentOS, it is upstream only from a user perspective, not from a code perspective.

> 
> > Removing the branch implies that history is erased. I do not think it is a valid action.
> 
> The tags still reference the commits and therefore they will not be lost. Only the bump commit to 0.1.4 could be garbage collected but it does not contain any useful information.

Someone else may want to fork and continue work on 0.1 and support users.
Whatever has been posted officially on upstream, especially stable release branches are not suppose to be erased in order to preserve history.
We can see huge projects that keep their stable versioning branches intact (e.g. https://github.com/kubernetes/kubernetes).

> 
> > nmstate-0.2 is targeted towards CentOS 8.2 and Fedora 32. In the meantime it is tested and known to work with CentOS 8.1 that is patched with NetworkManager 1.22.
> > Users are left therefore with nmstate-0.1 if they want to use official distribution versions.
> 
> I am not sure what you are getting at, here.

Explaining why we cannot declare nmstate-0.1 support end.

**Comment by tyll** [comment]
> CentOS is considered upstream from a user point of view, it represent the community. From a code point of view, it is downstream because to comes from RHEL.
> nmstate-0.1 on Fedora 31 is considered upstream, right? Like CentOS, it is upstream only from a user perspective, not from a code perspective.

GItHub/Copr/PyPi/images in the container registry are upstream in the context that I meant. CentOS/RHEL/Fedora is downstream from this perspective. How they relate to each other does not matter from this perspective.

> > > Removing the branch implies that history is erased. I do not think it is a valid action.
> > 
> > 
> > The tags still reference the commits and therefore they will not be lost. Only the bump commit to 0.1.4 could be garbage collected but it does not contain any useful information.
> 
> Someone else may want to fork and continue work on 0.1 and support users.

Do you honestly believe that this is an option for nmstate-0.1?

> Whatever has been posted officially on upstream, especially stable release branches are not suppose to be erased in order to preserve history.

I do not agree with this generic rule. If keeping the branch in GitHub is very important to you, we can do this. However, as I wrote, the tags preserve the history of officially released stuff. Also we removed container images from DockerHub (for CentOS 7) and I think it is good to also clean up to a certain point.

> We can see huge projects that keep their stable versioning branches intact (e.g. https://github.com/kubernetes/kubernetes).
> 
> > > nmstate-0.2 is targeted towards CentOS 8.2 and Fedora 32. In the meantime it is tested and known to work with CentOS 8.1 that is patched with NetworkManager 1.22.
> > > Users are left therefore with nmstate-0.1 if they want to use official distribution versions.
> > 
> > 
> > I am not sure what you are getting at, here.
> 
> Explaining why we cannot declare nmstate-0.1 support end.

Users can still get patches in Fedora as a downstream fix if there is actually a bug report or someone interested to do the patching there. You wrote yourself that there are no plans to backport any fixed to nmstate-0.1, even though we know that there are bugs that we fixed in later version.

**Comment by EdDev** [comment]
Summarizing my feedback:
- I’m good with removing nmstate-0.1 copr.
- Source stable brach should not be removed.
- We will support nmstate-0.1 on Fedora 31 and CentOS 8.1 until Fedora 32 and CentOS 8.2 arrive to the community.

I believe the chances are low for anyone asking support on 0.1 due to the low exposure at this time.

**Comment by tyll** [comment]
> * We will support nmstate-0.1 on Fedora 31 and CentOS 8.1 until Fedora 32 and CentOS 8.2 arrive to the community.

What do you mean with this? What specific tasks are you expecting to happen upstream/here on GitHub/Copr/the container registry for this?

Do you want to keep building nmstate-0.2 for Fedora 31 - but that would not be "supporting nmstate-0.1". You did not comment on this part from my original proposal.

**Comment by tyll** [comment]
Removed nmstate-0.1 Coprs from the README: #842
