### ISSUE TITLE
Test `test_nm_ovs_plugin_missing` fails all following OVS tests

### ISSUE THREAD

**Issue by EdDev** [nmstate/nmstate#759]
The `tests/integration/ovs_test.py::test_nm_ovs_plugin_missing` test is breaking all OVS following tests because it is not able to re-install the `NetworkManager-ovs` package.

See errors from the logs:
```
DEBUG    root:cmdlib.py:40 dnf install -y --cacheonly NetworkManager-ovs (cwd None)
DEBUG    root:cmdlib.py:53 FAILED: <err> = b'error: rpmdb: damaged header #178 retrieved -- skipping.\nerror: rpmdb: damaged header #179 retrieved -- skipping.\nerror: rpmdbNextIterator: skipping h#     179 blob size(1752749994): BAD, 8 + 16 * il(1886415219) + dl(1634877554)\nerror: rpmdbNextIterator: skipping h#     178 blob size(7736): BAD, 8 + 16 * il(71) + dl(6592)\nError opening file for checksum: /var/cache/dnf/copr:copr.fedorainfracloud.org:networkmanager:NetworkManager-1.22-25c098209a2a8596/packages/NetworkManager-ovs-1.22.6-2.el8.x86_64.rpm\nPackage "NetworkManager-ovs-1:1.22.6-2.el8.x86_64" from repository "copr:copr.fedorainfracloud.org:networkmanager:NetworkManager-1.22" has incorrect checksum\nError: Some packages have invalid cache, but cannot be downloaded due to "--cacheonly" option\n'; <rc> = 1
```

In addition, the test needs to assure that the plugin is installed before proceeding, making it clear what is the problem (currently it is hidden by the ovs xfail markings).

**Comment by tyll** [comment]
Looks to me like it is the same problem as #740

**Comment by tyll** [comment]
IMHO a better solution for the plugin tests would be to run them in seperate containers where the plugin is missing and then the container is discarded after the test ran.

**Comment by ffmancera** [comment]
#767 should fix this. Thanks!
