### ISSUE TITLE
DHCP timeout will cause software interface deleted in `libnmstate.show()`.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#775]
The NM will delete the device if DHCP timeout on software interface(like bond).

nmstate is using `NM.Client.get_devices()` for the interface list.

**Comment by cathay4t** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1783891

**Comment by cathay4t** [comment]
@ffmancera @tyll @EdDev I recall you guys talk about this issue in a meeting. Can anyone of you input anything valuable here before I consult with NM guys?

**Comment by EdDev** [comment]
This is what we do in VDSM to make sure the devices are not deleted:
https://github.com/oVirt/vdsm/blob/2ce23206ab39f2a6a8f6d236fb44200fd950268d/static/etc/NetworkManager/conf.d/vdsm.conf#L12

We need to add this in nmstate as this seems to make more sense as the default.
There is however another issue with RA infinite timeout, which NM does not support yet and we need to probably use sysfs to set.

**Comment by ffmancera** [comment]
Could we closed this? @cathay4t

**Comment by cathay4t** [comment]
Fix has been included in master and v0.2.6.
