### ISSUE TITLE
Unable to create DNS configuration

### ISSUE THREAD

**Issue by mardim91** [nmstate/nmstate#791]
Unable to create some DNS configuration with nmstate v0.2.3. 

the yaml the I used in my first try:

---
dns-resolver:
  config:
    search:
    - example.com
    - example.org
    server:
    - 8.8.8.8

Error:

Traceback (most recent call last):
  File "/usr/local/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.2.3', 'console_scripts', 'nmstatectl')()
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 217, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 241, in apply_state
    rollback_timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/nm/nmclient.py", line 98, in wrapped
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/netapplier.py", line 61, in apply
    validator.validate_capabilities(desired_state, netinfo.capabilities())
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/validator.py", line 60, in validate_capabilities
    validate_interface_capabilities(state[Constants.INTERFACES], capabilities)
KeyError: 'interfaces'

---------------------------------------------------------------------------------------------

The yaml I used in the second try: 

---
dns-resolver:
  config:
    search:
    - example.com
    - example.org
    server:
    - 8.8.8.8
interfaces: []

Error: 

Traceback (most recent call last):
  File "/usr/local/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.2.3', 'console_scripts', 'nmstatectl')()
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 217, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/nmstatectl/nmstatectl.py", line 241, in apply_state
    rollback_timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/nm/nmclient.py", line 98, in wrapped
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/netapplier.py", line 67, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/netapplier.py", line 128, in _apply_ifaces_state
    metadata.generate_ifaces_metadata(desired_state, current_state)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/metadata.py", line 74, in generate_ifaces_metadata
    _generate_dns_metadata(desired_state, current_state)
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/metadata.py", line 260, in _generate_dns_metadata
    searches,
  File "/usr/local/lib/python3.7/dist-packages/nmstate-0.2.3-py3.7.egg/libnmstate/metadata.py", line 280, in _save_dns_metadata
    "name servers: %s" % server
libnmstate.error.NmstateValueError: Failed to find suitable interface for saving DNS name servers: 8.8.8.8

**Comment by tyll** [comment]
Thank you for your report. What is the output of `nmstatectl show`?

**Comment by mardim91** [comment]
---
dns-resolver:
  config:
    search: []
    server: []
  running:
    search: []
    server:
    - 192.168.122.1
route-rules:
  config: []
routes:
  config:
  - destination: 0.0.0.0/0
    metric: 104
    next-hop-address: 192.168.123.1
    next-hop-interface: ens9
    table-id: 254
  running:
  - destination: 10.244.0.0/24
    metric: 0
    next-hop-address: ''
    next-hop-interface: cni0
    table-id: 254
  - destination: 172.17.0.0/16
    metric: 0
    next-hop-address: ''
    next-hop-interface: docker0
    table-id: 254
  - destination: 0.0.0.0/0
    metric: 100
    next-hop-address: 192.168.122.1
    next-hop-interface: ens3
    table-id: 254
  - destination: 192.168.122.0/24
    metric: 100
    next-hop-address: ''
    next-hop-interface: ens3
    table-id: 254
  - destination: 192.168.123.0/24
    metric: 107
    next-hop-address: ''
    next-hop-interface: ens7
    table-id: 254
  - destination: 192.168.123.0/24
    metric: 106
    next-hop-address: ''
    next-hop-interface: ens8
    table-id: 254
  - destination: 0.0.0.0/0
    metric: 104
    next-hop-address: 192.168.123.1
    next-hop-interface: ens9
    table-id: 254
  - destination: 192.168.123.0/24
    metric: 104
    next-hop-address: ''
    next-hop-interface: ens9
    table-id: 254
  - destination: fe80::/64
    metric: 256
    next-hop-address: ''
    next-hop-interface: cni0
    table-id: 254
  - destination: fe80::/64
    metric: 256
    next-hop-address: ''
    next-hop-interface: ens3
    table-id: 254
  - destination: ff00::/8
    metric: 256
    next-hop-address: ''
    next-hop-interface: cni0
    table-id: 255
  - destination: ff00::/8
    metric: 256
    next-hop-address: ''
    next-hop-interface: ens3
    table-id: 255
interfaces:
- name: cni0
  type: linux-bridge
  state: up
  bridge:
    options:
      group-forward-mask: 0
      mac-ageing-time: 300
      multicast-snooping: true
      stp:
        enabled: false
        forward-delay: 15
        hello-time: 2
        max-age: 20
        priority: 32768
    port: []
  ipv4:
    address:
    - ip: 10.244.0.1
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    address:
    - ip: fe80::a4fb:ecff:fe71:587a
      prefix-length: 64
    autoconf: false
    dhcp: false
    enabled: true
  mac-address: A6:FB:EC:71:58:7A
  mtu: 1450
- name: docker0
  type: linux-bridge
  state: up
  bridge:
    options:
      group-forward-mask: 0
      mac-ageing-time: 300
      multicast-snooping: true
      stp:
        enabled: false
        forward-delay: 15
        hello-time: 2
        max-age: 20
        priority: 32768
    port: []
  ipv4:
    address:
    - ip: 172.17.0.1
      prefix-length: 16
    dhcp: false
    enabled: true
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  mac-address: 02:42:1C:A6:D4:42
  mtu: 1500
- name: ens3
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.122.225
      prefix-length: 24
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    dhcp: true
    enabled: true
  ipv6:
    address:
    - ip: fe80::5054:ff:fe73:5832
      prefix-length: 64
    autoconf: false
    dhcp: false
    enabled: true
  mac-address: 52:54:00:73:58:32
  mtu: 1500
- name: ens7
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.123.143
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  mac-address: 52:54:00:4B:73:5F
  mtu: 1400
- name: ens8
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.123.126
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  mac-address: 52:54:00:4A:72:5F
  mtu: 1500
- name: ens9
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.123.142
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  mac-address: 52:54:00:4A:72:5A
  mtu: 1500
- name: flannel.1
  type: vxlan
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  mac-address: E6:47:80:E8:46:0D
  mtu: 1450
  vxlan:
    base-iface: ens3
    destination-port: 0
    id: 1
    remote: ''
- name: lo
  type: unknown
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  mtu: 65536
- name: veth0052de1d
  type: ethernet
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  mac-address: 46:87:C4:05:A7:2B
  mtu: 1450
- name: veth327f9a63
  type: ethernet
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  mac-address: B6:F5:81:47:B4:A4
  mtu: 1450

**Comment by ffmancera** [comment]
Thank you! I will take care of this
