### ISSUE TITLE
libnmstate.validator.validate_bridge is only used in test

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#825]
The `libnmstate.validator.validate_bridge` and similar functions is not used in production code.

**Comment by tyll** [comment]
Should it be moved to the tests or should the production code be adjusted to actually use it?

**Comment by ffmancera** [comment]
I am updating PR #861. This PR is going to fix this.

**Comment by ffmancera** [comment]
PR #909 fixed this. Closing.
