### ISSUE TITLE
Add example for routing rules

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#826]
This needs cleanup of #633

**Comment by adwait-thattey** [comment]
Hello
Can I take this one up?
Some pointers will be helpful

**Comment by adwait-thattey** [comment]
I am a bit confused about what needs to be done here. 
Do I have to rewrite the examples in that PR with the suggestions given in the comments?

**Comment by cathay4t** [comment]
@adwait-thattey Thank you. That PR require some code changes in test and might not suitable for good first issue. I will revive my own PR and continue work on it.

**Comment by ffmancera** [comment]
This is currently done, examples can be found in: https://github.com/nmstate/nmstate/blob/base/examples/eth1_add_route_rule.yml
