### ISSUE TITLE
vlan: removing a vlan base interface does not implicitly remove its dependent vlans

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#835]
Steps to reproduce:
1. Create a vlan base interface
2. Create some vlans using that base interface
3. Remove the base interface

Expected:
The vlans that depend on the removed base interface should have been removed.

Actual:
The vlans that depend on the removed base interface have not been removed.

**Comment by tyll** [comment]
Is the behavior really expected? We had a similar issue with bridges and slaves and we did not want to remove the slaves if the bridge was removed IIRC. @EdDev what is your opinion?

**Comment by EdDev** [comment]
If the base interface of a vlan is removed, any vlan on top of it cannot exist anymore.
