### ISSUE TITLE
Need better error message when openvswitch is not started.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#837]
When openvswitch is not started, we got libnm error with:

```
2020-02-24 20:13:04,092 root         ERROR    NM main-loop aborted: 
Connection activation failed on ovs0: reason=<enum 
NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED of type 
NM.ActiveConnectionStateReason>
```

Need better error message.

**Comment by tyll** [comment]
User story:

As an Nmstate API user, when I specify or change an OVS interface but the openvswitch service is unavailable, `libnmstate.apply()` raises an appropriate exception.

Implementation ideas:
During validation, if a ovs interface is specified:
- Check with systemd if openvswitch service is running and raise if not
- or: Check if ovs-vsctl command works and raise if not

**Comment by ffmancera** [comment]
> User story:
> 
> As an Nmstate API user, when I specify or change an OVS interface but the openvswitch service is unavailable, `libnmstate.apply()` raises an appropriate exception.
> 
> Implementation ideas:
> During validation, if a ovs interface is specified:
> 
>     * Check with systemd if openvswitch service is running and raise if not
> 
>     * or: Check if ovs-vsctl command works and raise if not

In my opinion the systemd approach is better. Also we should do this for teamd service. Thanks!
