### ISSUE TITLE
Save log to file in Travis

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#866]
When a job in Travis fails, the logs are uploaded for later inspection. This lacks the pytest logs.

Task: Adjust pytest to also log to a file and ensure that the file will be uploaded on failure. This probably needs a `--log-file` for pytest in run-tests.sh that stores the logfile in the directory that is uploaded to the log storage server. Ideally, this would also include some machine-readable log, there might be some JSON output available.

**Comment by biswajitpatra** [comment]
i would like to take up this issue

**Comment by biswajitpatra** [comment]
I guess the pytest logging is being done already
https://github.com/nmstate/nmstate/blob/a1eff46cc1eee4f5cc8906c3232601a70c2d7f9f/automation/run-tests.sh#L21-L28
&
https://github.com/nmstate/nmstate/blob/a1eff46cc1eee4f5cc8906c3232601a70c2d7f9f/automation/run-tests.sh#L143-L144

**Comment by ffmancera** [comment]
@UnversedBlood Would you like to look into this issue? Thanks!

**Comment by UnversedBlood** [comment]
> @UnversedBlood Would you like to look into this issue? Thanks!

I will look into this issue, thanks for the heads up!

**Comment by ffmancera** [comment]
Done in #1045. Thanks!
