### ISSUE TITLE
Runtime slave interface of bridge is not been showed in 'nmstatectl show'

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#869]
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1806452

**Comment by ffmancera** [comment]
I am not able to reproduce this in nmstate 0.2.6. I will open a PR with a test on this.

**Comment by ffmancera** [comment]
We are investigating a bug on NM. When using `NM.DeviceBridge.get_slaves()` it is returning an empty list if the bridge is not managed by NM.

**Comment by ffmancera** [comment]
Yes, it is a bug in NM. https://bugzilla.redhat.com/show_bug.cgi?id=1809547

**Comment by ffmancera** [comment]
I am going to workaround this looking into sysfs. This is going to take a while to fix according to NM folks.

**Comment by cathay4t** [comment]
If possible, please also include detecting vlan filtering via sysfs.
