### ISSUE TITLE
RFE: implement nmstatectl --version

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#884]
User story:
As a user, I can get the current version of nmstate by running nmstatectl --version.

**Comment by IsmayilMirzali** [comment]
@tyll Could this potentially be assigned to me?

**Comment by tyll** [comment]
sure, thank you, please go ahead.

**Comment by IsmayilMirzali** [comment]
@tyll I did look at ```nmstatectl.py``` and ```argparse.py``` but couldn't quite figure out where the new arg was supposed to be added. Any pointers? Thanks.

**Comment by ffmancera** [comment]
> @tyll I did look at `nmstatectl.py` and `argparse.py` but couldn't quite figure out where the new arg was supposed to be added. Any pointers? Thanks.

Hi! If you look into `nmstatectl.py`, you can see we are using the main function to create the parser and then `setup_subcommand_*()` functions to implement different nmstatectl commands. You will need to add a new subcommand function with the `--version` that should print the nmstate version.

In order to get the nmstate version, please look at `libnmstate/__init__.py`. Is that fine for you? Please, if you have any question, let me know. Thanks!

**Comment by IsmayilMirzali** [comment]
@ffmancera All clear.

**Comment by IsmayilMirzali** [comment]
@ffmancera So I think I managed to write the necessary code to provide the ```--version``` functionality but I am completely lost as to how to build or test if it works.

**Comment by ffmancera** [comment]
> @ffmancera So I think I managed to write the necessary code to provide the `--version` functionality but I am completely lost as to how to build or test if it works.

Sure, first I recommend you to look into [automation README.md](https://github.com/nmstate/nmstate/blob/master/automation/README.md). There you will find how to run all the tests using the container images. The tests are going to run with your code changes.

I recommend you to run the tests with the `--debug-shell` this way, you will land in the container shell with nmstate installed so you would be able to do `nmstatectl --version` and see what happens. If that is working, you should write an integration tests, please look at [tests/integration/nmstatectl_test.py](https://github.com/nmstate/nmstate/blob/master/tests/integration/nmstatectl_test.py).

Thank you!

**Comment by IsmayilMirzali** [comment]
> > @ffmancera So I think I managed to write the necessary code to provide the `--version` functionality but I am completely lost as to how to build or test if it works.
> 
> Sure, first I recommend you to look into [automation README.md](https://github.com/nmstate/nmstate/blob/master/automation/README.md). There, you will find how to run all the tests using the container images. The tests are going to run with your code changes.
> 
> I recommend you to run the tests with the `--debug-shell` this way, you will land in the container shell with nmstate installed so you would be able to do `nmstatectl --version` and see what happens. If that is working, you should write an integration tests, please look at [tests/integration/nmstatectl_test.py](https://github.com/nmstate/nmstate/blob/master/tests/integration/nmstatectl_test.py).
> 
> Thank you!

Running ```./automation/run-tests.sh --debug-shell``` launches a root prompt for me. (I assume inside a container). However the command ```nmstatectl``` does not get recognized. Output of my ```$PATH``` variable within the root shell:  
``` /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ```

**Comment by ffmancera** [comment]
You must run the test with `sudo`.

**Comment by IsmayilMirzali** [comment]
> You must run the test with `sudo`.

Thank you. That fixed. So all the changes I make to the code will be reflected within the debug shell?

**Comment by ffmancera** [comment]
> > You must run the test with `sudo`.
> 
> Thank you. That fixed. So all the changes I make to the code will be reflected within the debug shell?

Exactly. Thanks!

**Comment by tyll** [comment]
> > > You must run the test with `sudo`.
> > 
> > 
> > Thank you. That fixed. So all the changes I make to the code will be reflected within the debug shell?
> 
> Exactly. Thanks!

To clarify, currently it contains the code changes from when you started the script, see:
https://github.com/nmstate/nmstate/blob/master/automation/run-tests.sh#L329

You need to switch to /workspace/nmstate if you want the latest changes.

**Comment by IsmayilMirzali** [comment]
> > > > You must run the test with `sudo`.
> > > 
> > > 
> > > Thank you. That fixed. So all the changes I make to the code will be reflected within the debug shell?
> > 
> > 
> > Exactly. Thanks!
> 
> To clarify, currently it contains the code changes from when you started the script, see:
> https://github.com/nmstate/nmstate/blob/master/automation/run-tests.sh#L329
> 
> You need to switch to /workspace/nmstate if you want the latest changes.

And how would I exactly do that?

**Comment by IsmayilMirzali** [comment]
> > > You must run the test with `sudo`.
> > 
> > 
> > Thank you. That fixed. So all the changes I make to the code will be reflected within the debug shell?
> 
> Exactly. Thanks!

I actually managed to get it working with ```nmstatectl version```, however, adding it as ```--version``` is proving difficult since it would have to be added as an argument to ```parser```. (There may be another solution, so the code would look like:
```python
def main():
    logging.basicConfig(
        format="%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
        level=logging.DEBUG,
    )

    parser = argparse.ArgumentParser()

    subparsers = parser.add_subparsers()
    setup_subcommand_commit(subparsers)
    setup_subcommand_edit(subparsers)
    setup_subcommand_rollback(subparsers)
    setup_subcommand_set(subparsers)
    setup_subcommand_show(subparsers)
    parser.add_argument("--version", action="store_true", help="Display nmstate version")
    if len(sys.argv) == 1:
        parser.print_usage()
        return errno.EINVAL
    args = parser.parse_args()
    if args.version:
        display_version()
    return args.func(args)
```

**Comment by ffmancera** [comment]
Please provide a pull request in order to review it. Thanks!

**Comment by tyll** [comment]
> > To clarify, currently it contains the code changes from when you started the script, see:
> > https://github.com/nmstate/nmstate/blob/master/automation/run-tests.sh#L329
> > You need to switch to /workspace/nmstate if you want the latest changes.
> 
> And how would I exactly do that?

`cd /workspace/nmstate` inside the debug shell.
