### ISSUE TITLE
Use Netlink to get the runtime information instead of sysfs

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#899]
It would be very nice to use Netlink in order to retrieve the runtime information instead of reading from sysfs files. I am going to investigate this in my free time :-)

**Comment by IsmayilMirzali** [comment]
Can I potentially try this in case you're busy with some other issues?

**Comment by ffmancera** [comment]
Sorry but this is quite complex issue. We are currently working on this.

**Comment by tyll** [comment]
Is this a duplicate of #1136?

**Comment by tyll** [comment]
Closing as duplicate of #1136.
