### ISSUE TITLE
Checking libnm/NM version mismatch

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#903]
```
def nm_decode_version(v = None):
    if v is None:
        v = NM.utils_version()
    return ((v >> 16) & 0xFF,
            (v >>  8) & 0xFF,
            (v) & 0xFF)
```

You can also print it in in hex, which gives 0x11503, meaning
0x1.0x15.0x3, which is 1.21.3.

The major benefit of this encoding is that you can compare versions by
number.

```
def nm_encode_version(major, minor, micro):
    return (major << 16) | (minor << 8) | micro
...
if NM.utils_version() < nm_encode_version(1, 20, 0):
    warn("version missmatch")
```
or just
```
if NM.utils_version() < 0x11400: # 1.20.0
    warn("version missmatch")
```

**Comment by tanuja3** [comment]
I'm learning about how the code base works for GSoC project. Can I work on this issue?

**Comment by ffmancera** [comment]
Yes please, feel free to take it. I suggest you to read the CONTRIBUTING.md documentation before creating a pull request. Thanks! Let me know if you have any question.
