### ISSUE TITLE
Filter route rule by interface in `nmstatectl show <iface_name>`

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#935]
Currently `nmstatectl show <iface_name>` does not filter the route rule.

**Comment by cathay4t** [comment]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1785172

**Comment by adwait-thattey** [comment]
Does the filter needs to applied in the APIs itself or only in the cli client?

**Comment by adwait-thattey** [comment]
Can I try this one?

**Comment by ffmancera** [comment]
> Can I try this one?

I am sorry, there is someone else already working on this.
