### ISSUE TITLE
Lost default gateway when target interface not included in desire state.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#942]
Need fix the merge process to properly handle DNS and Route metatdata generation.

The problem could be simply reproduce by appply empty state with static DNS and gateway.

**Comment by cathay4t** [comment]
This issue also applied to route rules.

**Comment by cathay4t** [comment]
For anyone who want to help on this issue.

The merge process should be changed to:
 * Do full merge on all interfaces, then generate metadata to the full state.
 * Do normal merge from full merged state to desired state, so any interface required by DNS/Route/RouteRule will get full metadata.

**Comment by ffmancera** [comment]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1748389
