### ISSUE TITLE
Add support of LLDP

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#945]
* Use https://ovirt.org/develop/release-management/features/network/lldp.html
   as a base for formatting the report and expose the basic parameters.
 * Support LLDP for all physical interface types, including members of bridges
   and bonds.
 * In order to be able and learn the connected peer configuration and take
   decisions on how to configure our end.

**Comment by ffmancera** [comment]
I am taking this if you don't mind. Thanks!

**Comment by cathay4t** [comment]
Thanks

**Comment by tyll** [comment]
> I am taking this if you don't mind. Thanks!

Please make sure that this is clearly scoped to allow to finish this within one sprint. Otherwise split it into sub-tasks that can be finished in one sprint or quicker.

**Comment by ffmancera** [comment]
I am going to discuss this with @EdDev.

**Comment by tyll** [comment]
Old PR #64

**Comment by tyll** [comment]
Discussion of the schema: https://nmstate.atlassian.net/browse/NMSTATE-136
