### ISSUE TITLE
add_remove_ovs_bridge test stalled

### ISSUE THREAD

**Issue by vbenes** [nmstate/nmstate#948]
after running whole general feature from NM test suite (where nmstate CI test is the last one) I see timout and test stalled. 
This happens with 0.2.8 from 0313 as well as with master

`[root@beaker-networkmanager-custom-upstream-1706` NetworkManager-ci]# nmcli device 

DEVICE           TYPE           STATE                                  CONNECTION    
eth0             ethernet       connected                              System eth0   
eth1             ethernet       connected                              eth1          
ovs-br0          ovs-bridge     connected                              ovs-br0       
K_A7SMD0WmmNjuu  ovs-port       connected                              ovs-port-eth1 
t6N9wqcnu1RssMH  ovs-port       connected                              ovs-port-ovs0 
ovs0             ovs-interface  connecting (getting IP configuration)  ovs0          
eth1p            ethernet       unmanaged                              --            
eth2             ethernet       unmanaged                              --            
eth2p            ethernet       unmanaged                              --            
lo               loopback       unmanaged                              --     
`
log is here:
https://filepush.co/CrdW/journal_log.txt (search for t6N9wqcnu1RssMH to find the test beginning as there is some setup performed before)

I have a machine where I can reproduce. Ping me if you need one.

**Comment by ffmancera** [comment]
Waiting until release 0.2.9

**Comment by ffmancera** [comment]
Fixed by #1014.
