### ISSUE TITLE
Performance degrated on test case `test_lot_of_vlans_with_bridges`

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#974]
In master branch, it tooks 450 seconds:

https://travis-ci.com/github/nmstate/nmstate/jobs/299703268#L1327

In nmstate-0.2 branch, it tooks 147 seconds:

https://travis-ci.com/github/nmstate/nmstate/jobs/297744100#L1913

**Comment by cathay4t** [comment]
On the hand.
The whole integration test(without slow) performance improved from 16 minutes to 9 minutes.

My initial guess on this would be the block auto collect on Update2().

And maybe we can solve the problem of `test_lot_of_vlans_with_bridges` by activating unrelated profiles at once which will be done in https://github.com/nmstate/nmstate/issues/362

**Comment by cathay4t** [comment]
With mainloop fix, the test case `test_lot_of_vlans_with_bridges`  has improved to `1m19.341s`.

**Comment by ffmancera** [comment]
> With mainloop fix, the test case `test_lot_of_vlans_with_bridges` has improved to `1m19.341s`.

Thanks!

**Comment by cathay4t** [comment]
With PR #1016, the `test_lot_of_vlans_with_bridges` takes 99 seconds:

https://travis-ci.com/github/nmstate/nmstate/jobs/316870364#L1353

In master branch, it tooks 450 seconds:

https://travis-ci.com/github/nmstate/nmstate/jobs/299703268#L1327

In nmstate-0.2 branch, it tooks 147 seconds:

https://travis-ci.com/github/nmstate/nmstate/jobs/297744100#L1913
